### ISSUE TITLE
PDF.js v1.0.712 (build: 6969ed4)   Error: Command token too long: 128

### ISSUE THREAD

**Issue by winson2work** [mozilla/pdf.js#10048]
PDF.js v1.0.712 (build: 6969ed4)
信息：Command token too long: 128
堆栈：Error: Command token too long: 128
    at error (http://localhost:8080/webui/plugins/pdf/build/pdf.worker.js:249:9)
    at Lexer_getObj [as getObj] (http://localhost:8080/webui/plugins/pdf/build/pdf.worker.js:30268:11)
    at Parser_shift [as shift] (http://localhost:8080/webui/plugins/pdf/build/pdf.worker.js:29533:32)
    at Parser_makeStream [as makeStream] (http://localhost:8080/webui/plugins/pdf/build/pdf.worker.js:29736:12)
    at Parser_getObj [as getObj] (http://localhost:8080/webui/plugins/pdf/build/pdf.worker.js:29578:28)
    at XRef_fetchUncompressed [as fetchUncompressed] (http://localhost:8080/webui/plugins/pdf/build/pdf.worker.js:4212:28)
    at XRef_fetch [as fetch] (http://localhost:8080/webui/plugins/pdf/build/pdf.worker.js:4169:26)
    at XRef_fetchIfRef [as fetchIfRef] (http://localhost:8080/webui/plugins/pdf/build/pdf.worker.js:4150:19)
    at Dict_get [as get] (http://localhost:8080/webui/plugins/pdf/build/pdf.worker.js:3086:28)
    at Dict_getAll [as getAll] (http://localhost:8080/webui/plugins/pdf/build/pdf.worker.js:3132:20)

**Comment by Snuffleupagus** [comment]
When opening an issue, you need to provide *all* of the information as requested in [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md). Without any actionable information, e.g. the PDF file in question, the issue will be closed as incomplete.

**Comment by timvandermeij** [comment]
Closing since we need the PDF file in order to be able to analyze the problem. Moreover, version 1.0.712 is really old; use the most recent release and try to open the file with https://mozilla.github.io/pdf.js/web/viewer.html.
