### ISSUE TITLE
PDFjs.getMetadata() - XML parse bug

### ISSUE THREAD

**Issue by dhollenbeck** [mozilla/pdf.js#10395]
When getMetadata() is invoked on a specific PDF file, which I can not provide:
```js
var loader = pdfjs.getDocument(source);
loader.promise.then(function getDocumentSuccess(pdf) {
  pdf.getMetadata().then(function () {}).catch(...);
});
```
I get the following error:
```bash
(node:7452) TypeError: Cannot read property '0' of undefined
    at SimpleDOMNode.get (...\node_modules\pdfjs-dist\build\pdf.js:14097:29)
    at Metadata._parse (...\node_modules\pdfjs-dist\build\pdf.js:13740:19)
    at new Metadata (...\node_modules\pdfjs-dist\build\pdf.js:13698:12)
    at ...\pdfjs-dist\build\pdf.js:9421:34
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
I believe the following line of code is the line with the bug:
https://github.com/mozilla/pdf.js/blob/2ce489c16f0f642df1874c0da46aff5a4221de0a/src/display/xml_parser.js#L280-L282

Obviously, `this.childNodes` could be undefined as is the case with my pdf file. It is being invoked via an automatic property **get** function above:
https://github.com/mozilla/pdf.js/blob/66ffdc4c5b63a135f201508264761fce17c08059/src/display/metadata.js#L77

The offending XML document has the structure of:
```js
{ documentElement: SimpleDOMNode { nodeName: '#text', nodeValue: '﻿' } }
```

**Comment by timvandermeij** [comment]
@dhollenbeck Would it be possible to provide a test case without sensitive data here as well like you did for the other issue? Either a file or the XML itself is fine. This would allow us to add a unit test for this so we can avoid regressions in the future, and allow us to verify the fix.

**Comment by dhollenbeck** [comment]
Absolutely, @timvandermeij 
[toissue.pdf](https://github.com/mozilla/pdf.js/files/2727418/toissue.pdf)
