### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by jmorph99** [mozilla/pdf.js#10485]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version: UBuntu 18.04
- PDF.js version: latest
- Gulp 10.0.0
- Is a browser extension:

Steps to reproduce the problem:
1. git clone
2. git checkout -b john.murphy
3$ gulp test
[14:42:05] Using gulpfile /old1/home/murphy/newNetBeans/pdf.js/gulpfile.js
[14:42:05] Starting 'test'...
[14:42:05] Starting 'testing-pre'...
[14:42:05] Finished 'testing-pre' after 565 μs
[14:42:05] Starting 'generic'...
[14:42:05] Starting 'buildnumber'...

### Getting extension build number
Extension build number: 209
[14:42:05] Finished 'buildnumber' after 83 ms
[14:42:05] Starting 'locale'...

### Building localization files
[14:42:06] 'locale' errored after 1.27 s
[14:42:06] RangeError [ERR_OUT_OF_RANGE]: The value of "mode" is out of range. Received 33204
    at Object.fs.fchmod (fs.js:1024:11)
    at Object.fchmod (/old1/home/murphy/newNetBeans/pdf.js/node_modules/graceful-fs/polyfills.js:237:17)
    at mode (/old1/home/murphy/newNetBeans/pdf.js/node_modules/vinyl-fs/lib/file-operations.js:237:10)
    at onStat (/old1/home/murphy/newNetBeans/pdf.js/node_modules/vinyl-fs/lib/file-operations.js:227:14)
    at /old1/home/murphy/newNetBeans/pdf.js/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:150:5)
[14:42:06] 'generic' errored after 1.36 s
[14:42:06] 'test' errored after 1.36 s

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by jmorph99** [comment]
Sorry -

murphy@John-PC2:/old1/home/murphy/newNetBeans/pdf.js$ gulp --version
[14:54:18] CLI version 2.0.1
[14:54:18] Local version 4.0.0

**Comment by jmorph99** [comment]
node 10.0.0 was the issue
