### ISSUE TITLE
TypeError: current.txtElement.hasChildNodes is not a function

### ISSUE THREAD

**Issue by doublex** [mozilla/pdf.js#10705]
This PDF: 
[page4.pdf](https://github.com/mozilla/pdf.js/files/3031239/page4.pdf)

Command line:
````
node examples/node/pdf2svg.js /tmp/page4.pdf
````

Console:
````
# Document Loaded
Number of Pages: 1

# Page 1
Size: 700.157x830.551

Warning: Unimplemented graphic state BM
Warning: Unimplemented graphic state SMask
Error: TypeError: current.txtElement.hasChildNodes is not a function
    at SVGGraphics.endText (/tmp/pdf.js/build/dist/build/pdf.js:21347:126)
    at SVGGraphics_executeOpTree [as executeOpTree] (/tmp/pdf.js/build/dist/build/pdf.js:20983:20)
    at SVGGraphics_group [as group] (/tmp/pdf.js/build/dist/build/pdf.js:20866:14)
    at SVGGraphics_executeOpTree [as executeOpTree] (/tmp/pdf.js/build/dist/build/pdf.js:21147:20)
    at SVGGraphics_group [as group] (/tmp/pdf.js/build/dist/build/pdf.js:20866:14)
    at SVGGraphics_executeOpTree [as executeOpTree] (/tmp/pdf.js/build/dist/build/pdf.js:21147:20)
    at /tmp/pdf.js/build/dist/build/pdf.js:20919:18
````

**Comment by timvandermeij** [comment]
Thank you for writing clear issues! It really helps to get problems fixed quickly.
