### ISSUE TITLE
Windows bot is unresponsive

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#12459]
The Windows bot is not responding to commands. @brendandahl Could you give it a kick? We'll need to run makeref on it afterwards.

**Comment by brendandahl** [comment]
restarted

**Comment by timvandermeij** [comment]
It looks like the Windows bot is down again. Could you check it?

**Comment by brendandahl** [comment]
I'm also unable to connect with remote desktop. Tried rebooting from ec2 manager and no luck there either. Will have to dig into it tomorrow.

**Comment by brendandahl** [comment]
Should be back up now. I guess the AMI was retired, so I had to stop/start it.

**Comment by timvandermeij** [comment]
It looks like the bot is unresponsive again. Could you kick it @brendandahl?

**Comment by brendandahl** [comment]
kicked

**Comment by timvandermeij** [comment]
Unfortunately it seems to have died again. Are there logs that show why? If not, kicking it should help for now.

**Comment by timvandermeij** [comment]
Hm, it seems to have restored itself somehow.

**Comment by timvandermeij** [comment]
And it's down again :(

**Comment by brendandahl** [comment]
Should be back again...
When this happens I find firefox open on the bot and

```
Error: EPERM: operation not permitted, unlink 'C:\pdfjs\botio-files-pdfjs\private\e778f5e11d15691/node_modules/puppeteer/.local-firefox/win64-86.0a1/firefox/browser/features/doh-rollout@mozilla.org.xpi'
    at Object.unlinkSync (fs.js:956:3)
    at _unlinkSync (C:\pdfjs\botio\node_modules\shelljs\shell.js:1398:10)
    at rmdirSyncRecursive (C:\pdfjs\botio\node_modules\shelljs\shell.js:1145:9)
    at rmdirSyncRecursive (C:\pdfjs\botio\node_modules\shelljs\shell.js:1135:7)
    at rmdirSyncRecursive (C:\pdfjs\botio\node_modules\shelljs\shell.js:1135:7)
    at rmdirSyncRecursive (C:\pdfjs\botio\node_modules\shelljs\shell.js:1135:7)
    at rmdirSyncRecursive (C:\pdfjs\botio\node_modules\shelljs\shell.js:1135:7)
    at rmdirSyncRecursive (C:\pdfjs\botio\node_modules\shelljs\shell.js:1135:7)
    at rmdirSyncRecursive (C:\pdfjs\botio\node_modules\shelljs\shell.js:1135:7)
    at rmdirSyncRecursive (C:\pdfjs\botio\node_modules\shelljs\shell.js:1135:7)
```

**Comment by timvandermeij** [comment]
Hm, ok. It's good to have the stack trace. Not sure what to do with it given that it works most of the time and Puppeteer handles all of this now, but if it keeps on happening we can maybe look into filing an issue with Puppeteer, although that will be difficult without a clear reproducer. Thanks for now!
