### ISSUE TITLE
SVG: "Invalid SVG dimensions"

### ISSUE THREAD

**Issue by doublex** [mozilla/pdf.js#12996]
Steps to reproduce (this PDF):
[page4.pdf](https://github.com/mozilla/pdf.js/files/5990272/page4.pdf)

````
npm install
node_modules/.bin/gulp dist-install
node examples/node/pdf2svg.js /tmp/page4.pdf
````

Error:
````
Error: Invalid SVG dimensions
    at unreachable (/tmp/pdf.js/build/dist/legacy/build/pdf.js:2086:9)
    at assert (/tmp/pdf.js/build/dist/legacy/build/pdf.js:2091:5)
    at DOMSVGFactory.create (/tmp/pdf.js/build/dist/legacy/build/pdf.js:640:24)
    at SVGGraphics._makeTilingPattern (/tmp/pdf.js/build/dist/legacy/build/pdf.js:24178:36)
    at SVGGraphics._makeColorN_Pattern (/tmp/pdf.js/build/dist/legacy/build/pdf.js:24127:23)
    at SVGGraphics.setFillColorN (/tmp/pdf.js/build/dist/legacy/build/pdf.js:24088:39)
    at SVGGraphics.executeOpTree (/tmp/pdf.js/build/dist/legacy/build/pdf.js:23634:22)
    at /tmp/pdf.js/build/dist/legacy/build/pdf.js:23508:18
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
````

**Comment by Snuffleupagus** [comment]
Changing the code to get rid of `Error: Invalid SVG dimensions` such that the page isn't *completely* broken with the SVG-backend should be fairly easy, however that's unfortunately not guaranteed to to actually fix rendering completely in this case.
