### ISSUE TITLE
getStructTree not available on es5 build?

### ISSUE THREAD

**Issue by A-Babin** [mozilla/pdf.js#13423]
Hello!

I'm trying to parse some PDFs in a Node application. In particular, I'm targeting some tables. 

I see in the DOM of the web viewer rendering one of my documents that the `structTree` provides some really useful structural information that would make my life a lot easier, but the `Page.getStructTree` method is not available on `pdfjs-dist` es5 build that must be used in Node.js. 

Is there any other way I can get the struct tree information in Node? 

Thanks!

**Comment by timvandermeij** [comment]
The last pre-release was is from April 5 and the struct tree logic was merged on April 9 (see #13171) so it's indeed not released. You'll have to wait until the next release, which is likely to happen in the coming week.

**Comment by A-Babin** [comment]
Glad to hear that, thank you!

**Comment by barsdeveloper** [comment]
I am trying to inspect what type of information getStructTree contains for a similar purpose. Unfortunately I'm getting null from this method. Any idea why it could be like that?

I'm using rollup and commonjs to use this library
```JavaScript
import pdfjs from "pdfjs-dist"
import pdfjsWorker from "pdfjs-dist/build/pdf.worker.entry"

pdfjs.GlobalWorkerOptions.workerSrc = pdfjsWorker

let pdf = await pdfjs.getDocument("test.pdf").promise
let page = await pdf.getPage(3)
let tree = await page.getStructTree()
```

**Comment by mootari** [comment]
@barsdeveloper Structure trees aren't available in every PDF. You can find more details as well as pointers to example PDFs in https://github.com/mozilla/pdf.js/issues/6269

**Comment by avichovatiya67** [comment]
Facing the same issue.
What's the fix for this?


```
StructTree.js:47 Uncaught TypeError: page.getStructTree is not a function
    at loadStructTree (StructTree.js:47:1)
    at invokePassiveEffectCreate (react-dom.development.js:23487:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at flushPassiveEffectsImpl (react-dom.development.js:23574:1)
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
    at flushPassiveEffects (react-dom.development.js:23447:1)
    at react-dom.development.js:23324:1
    at workLoop (scheduler.development.js:417:1)
    at flushWork (scheduler.development.js:390:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:157:1)
```

and 

```
PageCanvas.js:61 Uncaught TypeError: Cannot read properties of undefined (reading 'ENABLE')
    at drawPageOnCanvas (PageCanvas.js:61:1)
    at invokePassiveEffectCreate (react-dom.development.js:23487:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at flushPassiveEffectsImpl (react-dom.development.js:23574:1)
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
    at flushPassiveEffects (react-dom.development.js:23447:1)
    at react-dom.development.js:23324:1
    at workLoop (scheduler.development.js:417:1)
    at flushWork (scheduler.development.js:390:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:157:1)
```
