### ISSUE TITLE
Type check JS with typescript

### ISSUE THREAD

**Issue by brendandahl** [mozilla/pdf.js#14017]
In mozilla-central some parts of the code base are now using typescript to do type checks on regular JS that is annotated with jsdoc comments. This could be nice to help us enforce documentation for the API and maybe prevent some bugs.

  Example [config](https://searchfox.org/mozilla-central/rev/d3a34b89169363b1f91eb75d4c7bdc397efb2e0c/devtools/client/performance-new/tsconfig.json) and JS files that are checked get [`@ts-check`](https://searchfox.org/mozilla-central/rev/d3a34b89169363b1f91eb75d4c7bdc397efb2e0c/devtools/client/performance-new/aboutprofiling/initializer.js#4).

**Comment by Snuffleupagus** [comment]
Given that we're shipping TypeScript definitions [in pdfjs-dist](https://github.com/mozilla/pdfjs-dist/tree/master/types), aren't we already doing this at least *partially*?

Please note https://github.com/mozilla/pdf.js/blob/064c21d360dd5a8bd0c9cfc6f16d4c135e7d106c/gulpfile.js#L1375-L1392 and https://github.com/mozilla/pdf.js/blob/064c21d360dd5a8bd0c9cfc6f16d4c135e7d106c/gulpfile.js#L1695-L1726 which runs on every commit/PR thanks to GitHub Actions via https://github.com/mozilla/pdf.js/blob/064c21d360dd5a8bd0c9cfc6f16d4c135e7d106c/gulpfile.js#L2350-L2357

**Comment by Snuffleupagus** [comment]
Looking at https://www.typescriptlang.org/docs/handbook/compiler-options.html#compiler-options, there's a [`checkJS` option](https://www.typescriptlang.org/tsconfig/#checkJs) that looks relevant here.

I tried adding that to our existing `tsc` arguments in the `gulp types` task, but only got a generic/unhelpful error message:
```
$ gulp types
[14:11:36] Using gulpfile ~\Git\pdf.js\gulpfile.js
[14:11:36] Starting 'types'...
### Generating TypeScript definitions using `tsc`
[14:11:47] 'types' errored after 11 s
[14:11:47] Error: Command failed: "node_modules/.bin/tsc" --target ES2020 --allo
wJS --checkJS --declaration --outDir build/types/ --strict --esModuleInterop --f
orceConsistentCasingInFileNames --emitDeclarationOnly --moduleResolution node sr
c/pdf.js web/pdf_viewer.component.js

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:314:20)
    at ChildProcess.EventEmitter.emit (domain.js:506:15)
    at maybeClose (internal/child_process.js:1022:16)
    at Socket.<anonymous> (internal/child_process.js:444:11)
    at Socket.emit (events.js:314:20)
    at Socket.EventEmitter.emit (domain.js:506:15)
    at Pipe.<anonymous> (net.js:675:12)
    at Pipe.callbackTrampoline (internal/async_hooks.js:126:14)
```
