### ISSUE TITLE
Fix integration test errors

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#14822]
I'm not entirely sure when this started happening, but recently all integration tests on the bots seem to fail; please see http://54.193.163.58:8877/e5b627524d19deb/output.txt for example. The stack trace is the following, which looking at #14293 could point to an upstream bug, but contrary to that issue this time it also involves the Windows bot and seemingly _all_ tests instead of a single one:

```
  Message:
[31m    ProtocolError: Protocol error (Target.createTarget): can't access property "addTab", tabBrowser is null addTab@chrome://remote/content/shared/TabManager.jsm:128:17
    createTarget@chrome://remote/content/cdp/domains/parent/Target.jsm:90:28
    execute@chrome://remote/content/cdp/domains/DomainCache.jsm:101:25
    execute@chrome://remote/content/cdp/sessions/Session.jsm:64:25
    onPacket@chrome://remote/content/cdp/CDPConnection.jsm:262:36
    onMessage@chrome://remote/content/server/WebSocketTransport.jsm:89:18
    handleEvent@chrome://remote/content/server/WebSocketTransport.jsm:71:14
    [0m
  Stack:
    error properties: Object({ originalMessage: 'can't access property "addTab", tabBrowser is null' })
    ProtocolError: Protocol error (Target.createTarget): can't access property "addTab", tabBrowser is null addTab@chrome://remote/content/shared/TabManager.jsm:128:17
    createTarget@chrome://remote/content/cdp/domains/parent/Target.jsm:90:28
    execute@chrome://remote/content/cdp/domains/DomainCache.jsm:101:25
    execute@chrome://remote/content/cdp/sessions/Session.jsm:64:25
    onPacket@chrome://remote/content/cdp/CDPConnection.jsm:262:36
    onMessage@chrome://remote/content/server/WebSocketTransport.jsm:89:18
    handleEvent@chrome://remote/content/server/WebSocketTransport.jsm:71:14
        at C:\pdfjs\botio-files-pdfjs\private\e5b627524d19deb\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:75:24
        at new Promise (<anonymous>)
        at Connection.send (C:\pdfjs\botio-files-pdfjs\private\e5b627524d19deb\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:71:16)
        at Browser._createPageInContext (C:\pdfjs\botio-files-pdfjs\private\e5b627524d19deb\node_modules\puppeteer\lib\cjs\puppeteer\common\Browser.js:274:53)
        at BrowserContext.newPage (C:\pdfjs\botio-files-pdfjs\private\e5b627524d19deb\node_modules\puppeteer\lib\cjs\puppeteer\common\Browser.js:553:30)
        at Browser.newPage (C:\pdfjs\botio-files-pdfjs\private\e5b627524d19deb\node_modules\puppeteer\lib\cjs\puppeteer\common\Browser.js:267:37)
        at C:\pdfjs\botio-files-pdfjs\private\e5b627524d19deb\test\integration\test_utils.js:19:42
        at Array.map (<anonymous>)
        at exports.loadAndWait (C:\pdfjs\botio-files-pdfjs\private\e5b627524d19deb\test\integration\test_utils.js:18:32)
        at UserContext.<anonymous> (C:\pdfjs\botio-files-pdfjs\private\e5b627524d19deb\test\integration\annotation_spec.js:230:21)
  Message:
[31m    TypeError: Cannot read property 'map' of undefined[0m
  Stack:
        at exports.closePages (C:\pdfjs\botio-files-pdfjs\private\e5b627524d19deb\test\integration\test_utils.js:49:11)
        at UserContext.<anonymous> (C:\pdfjs\botio-files-pdfjs\private\e5b627524d19deb\test\integration\annotation_spec.js:234:13)
        at <Jasmine>
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by calixteman** [comment]
The last good run:
https://github.com/mozilla/pdf.js/pull/14784#issuecomment-1100272124
The first failure is:
https://github.com/mozilla/pdf.js/pull/14777#issuecomment-1100634126
The pushlog around these dates:
https://hg.mozilla.org/mozilla-central/pushloghtml?startdate=04%2F14%2F2022&enddate=04%2F16%2F2022

**Comment by Snuffleupagus** [comment]
It seems, when testing locally, that skipping the following test "fixes" things: https://github.com/mozilla/pdf.js/blob/752dee5caa4e9e43b84c2e3036a1f3939f42320a/test/integration/scripting_spec.js#L448-L483

I recall that test having caused trouble in the past, see e.g. PR #14199, and I cannot help wonder if we now need to update that test-case to somehow work without the preference (since I'd imagine that it'll eventually be removed anyway)?

**Comment by calixteman** [comment]
It's related to:
https://hg.mozilla.org/mozilla-central/rev/a941cd19ec11
Locally, it works in removing the pref:
https://github.com/mozilla/pdf.js/blob/2be19e828fcf9ce7740a2136087da028dff56e00/test/test.js#L951

but in a m-c test an other pref has been added:
https://hg.mozilla.org/mozilla-central/diff/a941cd19ec11261de251c1c1cdcbae6da18fe835/toolkit/components/pdfjs/test/browser_pdfjs_savedialog.js
and locally it works too with this new one.
