### ISSUE TITLE
gulp server: ReferenceError: primordials is not defined error

### ISSUE THREAD

**Issue by avatar-lavventura** [mozilla/pdf.js#15250]
I am on macOS. I have followed the installation guide but when I run ` gulp server` I get `ReferenceError: primordials is not defined` error. How can I fix this error?

```
$ git clone https://github.com/mozilla/pdf.js.git
$ cd pdf.js
$ npm install -g gulp-cli
$ npm install --legacy-peer-deps
$ gulp --version
[14:13:56] CLI version 3.9.1
[14:13:56] Local version 3.9.1
$ npm --version
8.6.0
$ node --version
v18.7.0
$ gulp server
fs.js:47
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:47:5
    at req_ (/Users/alper/git/pdf.js/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/alper/git/pdf.js/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/alper/git/pdf.js/node_modules/gulp/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1022:19)
    at require (node:internal/modules/cjs/helpers:102:18)

Node.js v18.7.0
```

**Comment by Snuffleupagus** [comment]
> $ npm install --legacy-peer-deps
> $ gulp --version
> [14:13:56] CLI version 3.9.1
> [14:13:56] Local version 3.9.1

That looks strange, given the `gulp` version that we require; please note:
https://github.com/mozilla/pdf.js/blob/b8aa9c62217492c845ae3f27cc368aec7a58f38a/package.json#L33

Could you try running `npm install` instead (or if that doesn't work, `npm install -f`)?

If that still doesn't work, it's quite possible that it's actually a bug `gulp` or maybe it doesn't (yet) support the latest Node.js version. Does the current LTS release of Node.js work?

**Comment by xwk** [comment]
I had the same problem as @avatar-lavventura reported. But after I ran ```npm install gulp@4.0.2 --force``` , the problem was gone.

**Comment by kingaimaster94** [comment]
I can't solve this error in node version 22.0.

**Comment by kingaimaster94** [comment]
thanks.
I upgraded v20 and have solved this problem
