### ISSUE TITLE
ReferenceError: Path2D is not define

### ISSUE THREAD

**Issue by clement-estone** [mozilla/pdf.js#16237]
Hi there!

I'm currently using the `pdfjs-dist` package with `canvas` on Node.js. On some PDF everything works fine, but on some others, I get the following error:

```
ReferenceError: Path2D is not defined
    at compileType3Glyph (/home/xxxxxxxxxx/node_modules/.pnpm/pdfjs-dist@3.4.120/node_modules/pdfjs-dist/build/webpack:/pdfjs-dist/build/pdf/src/display/canvas.js:402:16)
    at CanvasGraphics.apply [as paintImageMaskXObject] (/home/xxxxxxxxxx/node_modules/.pnpm/pdfjs-dist@3.4.120/node_modules/pdfjs-dist/build/webpack:/pdfjs-dist/build/pdf/src/display/canvas.js:2860:26)
    at CanvasGraphics.executeOperatorList (/home/xxxxxxxxxx/node_modules/.pnpm/pdfjs-dist@3.4.120/node_modules/pdfjs-dist/build/webpack:/pdfjs-dist/build/pdf/src/display/canvas.js:1213:20)
    at CanvasGraphics.showType3Text (/home/xxxxxxxxxx/node_modules/.pnpm/pdfjs-dist@3.4.120/node_modules/pdfjs-dist/build/webpack:/pdfjs-dist/build/pdf/src/display/canvas.js:2427:14)
    at CanvasGraphics.apply [as showText] (/home/xxxxxxxxxx/node_modules/.pnpm/pdfjs-dist@3.4.120/node_modules/pdfjs-dist/build/webpack:/pdfjs-dist/build/pdf/src/display/canvas.js:2198:19)
    at CanvasGraphics.executeOperatorList (/home/xxxxxxxxxx/node_modules/.pnpm/pdfjs-dist@3.4.120/node_modules/pdfjs-dist/build/webpack:/pdfjs-dist/build/pdf/src/display/canvas.js:1213:20)
    at InternalRenderTask._next (/home/xxxxxxxxxx/node_modules/.pnpm/pdfjs-dist@3.4.120/node_modules/pdfjs-dist/build/webpack:/pdfjs-dist/build/pdf/src/display/api.js:3378:37)
    at processTicksAndRejections (node:internal/process/task_queues:95:5
```

I'm using the latest versions: `pdfjs-dist v3.4.120` and `canvas v2.11.0` on Node.js `19.4.0` through Volta.
I'm using the Nest.js framework whose core is at the `9.2.1` version.

I can't unfortunately share the PDFs as they contain sensitive informations.

**Comment by Snuffleupagus** [comment]
There's a polyfill specifically for Node.js environments; please see https://github.com/mozilla/pdf.js/blob/09da8026b6fd803d60451aaf0aa8349383468baa/src/shared/compatibility.js#L27-L37
However in Node.js environments you *must* use a `legacy`-build of the PDF.js library, otherwise it's not guaranteed to work; please note https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support and also https://www.npmjs.com/package/pdfjs-dist?activeTab=readme

> I'm using the latest versions: `pdfjs-dist v3.4.120` and `canvas v2.11.0` on Node.js `19.4.0` through Volta.
> I'm using the Nest.js framework whose core is at the `9.2.1` version.

Unfortunately we don't know what either "Volta" or "Nest.js" is, and please keep in mind that we can't provide help/support for the plethora of frameworks that exist.
