### ISSUE TITLE
ExternalDocument can not create pdf from buffer

### ISSUE THREAD

**Issue by gitti20M** [mozilla/pdf.js#16231]
Configuration:
- Chrome Version 111.0.5563.147 (Offizieller Build) (64-Bit)
- Windows 10
- PDF.js version: 2.4.7

I get the following error when I run this:

 ```
fs.readFile(file, (err, data) => {
                if (!err) {
                    const externalDoc: ExternalDocument;

                    externalDoc = new ExternalDocument(data);
                        
                    doc.addPagesOf(externalDoc);
                }
         });
```

Error: Invalid number at 1: (code: 32)
at Lexer._error (/home/superuser/spesen/node_modules/pdfjs/lib/parser/lexer.js:152:11)
at Lexer.readNumber (/home/superuser/spesen/node_modules/pdfjs/lib/parser/lexer.js:180:16)
at parseObject (/home/superuser/spesen/node_modules/pdfjs/lib/object/reference.js:99:33)
at PDFReference.get [as object] (/home/superuser/spesen/node_modules/pdfjs/lib/object/reference.js:15:17)
at new ExternalDocument (/home/superuser/spesen/node_modules/pdfjs/lib/external.js:20:42)
at /home/superuser/spesen/src/pdf/pdfGenerator.ts:49:59
at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)

The pdf file is DB (Deutsche Bahn) ticket.

**Comment by Snuffleupagus** [comment]
Most likely this issue was opened against the wrong project, since the code-snippet contains functions that we don't provide and the stack-trace also references code that doesn't exist in this project.
