### ISSUE TITLE
Fix integration test "Interaction in doc_actions.pdf for page actions must execute PageOpen and PageClose actions"

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#16928]
Introduction date: January 6, 2021
Introduction PR: https://github.com/mozilla/pdf.js/commit/6523f8880bd91cf1f8ccbf0215dd7e1ea1590e9f (/cc @calixteman)
Type: intermittent (sometimes it works, indicating a possible timing/waiting issue)
OS: Windows
Logs: http://54.193.163.58:8877/248efa3bf526b9a/output.txt
Traceback:

```
Failures:
2) Interaction in doc_actions.pdf for page actions must execute PageOpen and PageClose actions
  Message:
[31m    Error: Timeout - Async function did not complete within 30000ms (set by jasmine.DEFAULT_TIMEOUT_INTERVAL)[0m
  Stack:
        at <Jasmine>
        at listOnTimeout (node:internal/timers:569:17)
        at process.processTimers (node:internal/timers:512:7
        
<snip>

Suite error: Interaction in doc_actions.pdf for page actions
  Message:
[31m    TargetCloseError: Protocol error (Runtime.callFunctionOn): Target closed[0m
  Stack:
        at CallbackRegistry.clear (file:///C:/pdfjs/botio-files-pdfjs/private/248efa3bf526b9a/node_modules/puppeteer-core/lib/esm/puppeteer/common/Connection.js:134:36)
        at CDPSessionImpl._onClosed (file:///C:/pdfjs/botio-files-pdfjs/private/248efa3bf526b9a/node_modules/puppeteer-core/lib/esm/puppeteer/common/Connection.js:480:25)
        at Connection.onMessage (file:///C:/pdfjs/botio-files-pdfjs/private/248efa3bf526b9a/node_modules/puppeteer-core/lib/esm/puppeteer/common/Connection.js:243:25)
        at Immediate.<anonymous> (file:///C:/pdfjs/botio-files-pdfjs/private/248efa3bf526b9a/node_modules/puppeteer-core/lib/esm/puppeteer/common/NodeWebSocketTransport.js:47:36)
        at process.processImmediate (node:internal/timers:476:21)
        
<snip>

Jasmine received a result after the suite finished:
{
  matcherName: '',
  message: 'TargetCloseError: Protocol error (Input.dispatchKeyEvent): Target closed',
  stack: '    at CallbackRegistry.clear (file:///C:/pdfjs/botio-files-pdfjs/private/248efa3bf526b9a/node_modules/puppeteer-core/lib/esm/puppeteer/common/Connection.js:134:36)\n' +
    '    at CDPSessionImpl._onClosed (file:///C:/pdfjs/botio-files-pdfjs/private/248efa3bf526b9a/node_modules/puppeteer-core/lib/esm/puppeteer/common/Connection.js:480:25)\n' +
    '    at #onClose (file:///C:/pdfjs/botio-files-pdfjs/private/248efa3bf526b9a/node_modules/puppeteer-core/lib/esm/puppeteer/common/Connection.js:279:21)\n' +
    '    at WebSocket.<anonymous> (file:///C:/pdfjs/botio-files-pdfjs/private/248efa3bf526b9a/node_modules/puppeteer-core/lib/esm/puppeteer/common/NodeWebSocketTransport.js:53:30)\n' +
    '    at callListener (C:\\pdfjs\\botio-files-pdfjs\\private\\248efa3bf526b9a\\node_modules\\ws\\lib\\event-target.js:290:14)\n' +
    '    at WebSocket.onClose (C:\\pdfjs\\botio-files-pdfjs\\private\\248efa3bf526b9a\\node_modules\\ws\\lib\\event-target.js:220:9)\n' +
    '    at WebSocket.emit (node:events:513:28)\n' +
    '    at WebSocket.emitClose (C:\\pdfjs\\botio-files-pdfjs\\private\\248efa3bf526b9a\\node_modules\\ws\\lib\\websocket.js:258:10)\n' +
    '    at Socket.socketOnClose (C:\\pdfjs\\botio-files-pdfjs\\private\\248efa3bf526b9a\\node_modules\\ws\\lib\\websocket.js:1264:15)\n' +
    '    at Socket.emit (node:events:513:28)',
  passed: false,
  expected: '',
  actual: '',
  code: undefined
}
```

**Comment by calixteman** [comment]
It has been fixed thanks to #17036.
