### ISSUE TITLE
Fix integration test "Interaction in bug1844576.pdf must check that a field has the correct formatted value"

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#16930]
Introduction date: July 21, 2023
Introduction PR: https://github.com/mozilla/pdf.js/commit/9277801493691da0f2de8b282fa3d2d4a9c0d537 (/cc @calixteman)
Type: intermittent (sometimes it works, indicating a possible timing/waiting issue)
OS: Windows
Logs: http://54.193.163.58:8877/248efa3bf526b9a/output.txt
Traceback:

```
Failures:
4) Interaction in bug1844576.pdf must check that a field has the correct formatted value
  Message:
[31m    In firefox: Expected false to equal true.[0m
  Stack:
        at <Jasmine>
        at C:\pdfjs\botio-files-pdfjs\private\248efa3bf526b9a\test\integration\scripting_spec.js:2029:14
        at runNextTicks (node:internal/process/task_queues:60:5)
        at process.processImmediate (node:internal/timers:447:9)
        at async Promise.all (index 0)
  Message:
[31m    In firefox: Expected false to equal true.[0m
  Stack:
        at <Jasmine>
        at C:\pdfjs\botio-files-pdfjs\private\248efa3bf526b9a\test\integration\scripting_spec.js:2040:14
        at runNextTicks (node:internal/process/task_queues:60:5)
        at process.processImmediate (node:internal/timers:447:9)
        at async Promise.all (index 0)
```

**Comment by timvandermeij** [comment]
I suspect this one, and most of the other integration test flakiness, is because of hardcoded sleeps using e.g. `waitForTimeout`. Those should generally be avoided because they are a source of intermittent problems: if the bots are ever so slightly slower, the hardcoded timeout value may not be enough and the test fails randomly as a result. This also makes it very hard to reproduce locally.

Moreover, the `waitForTimeout` is marked as obsolete on https://pptr.dev/api/puppeteer.page.waitfortimeout. Finally, the remarks section at https://pptr.dev/api/puppeteer.page.waitfortimeout#remarks confirms what I wrote above: instead of a fixed timeout we should be awaiting e.g. the presence of the element we're inspecting. That eliminates all need for fixed waits.

**Comment by timvandermeij** [comment]
I have a patch locally that is confirmed to fix the issue here, but I would like to see if there is room for more cleanup. I'll try to provide a PR for this next weekend, and that approach can then also serve as an example for the other intermittents we have left (because I have been looking at them in a broader scope).
