### ISSUE TITLE
Fix integration test "Interaction Textfields and focus must check that focus/blur callbacks aren't called"

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#17089]
Introduction date: September 5, 2021
Introduction PR: https://github.com/mozilla/pdf.js/commit/d03494eeff496547bfd9001c3ccacd7a89ecae6f (/cc @calixteman)
Type: intermittent (sometimes it works, indicating a possible timing/waiting issue)
OS: Linux
Logs: http://54.241.84.105:8877/6ce0d1567eb597b/output.txt
Traceback:

```
Failures:
2) Interaction Textfields and focus must check that focus/blur callbacks aren't called
  Message:
[31m    ProtocolError: Input.dispatchMouseEvent timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.[0m
  Stack:
        at <instance_members_initializer> (file:///home/ubuntu/pdfjs/botio-files-pdfjs/private/6ce0d1567eb597b/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:39:14)
        at new Callback (file:///home/ubuntu/pdfjs/botio-files-pdfjs/private/6ce0d1567eb597b/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:43:16)
        at CallbackRegistry.create (file:///home/ubuntu/pdfjs/botio-files-pdfjs/private/6ce0d1567eb597b/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:82:26)
        at Connection._rawSend (file:///home/ubuntu/pdfjs/botio-files-pdfjs/private/6ce0d1567eb597b/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:203:26)
        at CdpCDPSession.send (file:///home/ubuntu/pdfjs/botio-files-pdfjs/private/6ce0d1567eb597b/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/CDPSession.js:58:33)
        at file:///home/ubuntu/pdfjs/botio-files-pdfjs/private/6ce0d1567eb597b/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Input.js:283:37
        at #withTransaction (file:///home/ubuntu/pdfjs/botio-files-pdfjs/private/6ce0d1567eb597b/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Input.js:244:19)
        at CdpMouse.move (file:///home/ubuntu/pdfjs/botio-files-pdfjs/private/6ce0d1567eb597b/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Input.js:275:40)
        at CdpMouse.click (file:///home/ubuntu/pdfjs/botio-files-pdfjs/private/6ce0d1567eb597b/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Input.js:346:31)
        at /home/ubuntu/pdfjs/botio-files-pdfjs/private/6ce0d1567eb597b/test/integration/freetext_editor_spec.js:2563:28
```

Additional notes: this is one of the integration tests that still uses `waitForTimeout` which is likely to contribute to this issue.

**Comment by timvandermeij** [comment]
Upon closer inspection I noticed that this traceback actually has the source in it in the last line, namely the freetext editor spec. However, this failing test lives in the scripting spec! That means that this test failing is yet again a side-effect from the problem in #17087: something times out in the free text spec and that leads to another test failing because the protocol error is raised later when the test runner has already moved on.

Closing this issue since this test doesn't seem to be the culprit here.
