### ISSUE TITLE
Browser shows PDF but PDF.js does not - Page dictionary kid reference points to wrong type of object

### ISSUE THREAD

**Issue by hrvoj3e** [mozilla/pdf.js#17163]
I don't know if this is fixable but a similar bug has been solved before so ...
    https://github.com/mozilla/pdf.js/issues/9540

Attach (recommended) or Link to PDF file here:
I can provide such PDF via private channel.

Configuration:
- Web browser and its version: Vivaldi 6.2.3105.58
- PDF.js version: `3.11.174` and `3.9.179`
- Is a browser extension: NO

PDF 595b0a421a1af121027d006ca6564707 [1.7 www.ilovepdf.com / EXCEL.EXE] (PDF.js: 3.11.174 [ce8716743])

Steps to reproduce the problem:
Load PDF in viewer.

What is the expected behavior? (add screenshot)
Render PDF.

What went wrong? (add screenshot)

```
Page dictionary kid reference points to wrong type of object

pdf_viewer.js:1018 Unable to initialize viewer 
UnknownErrorException {message: 'Page dictionary kid reference points to wrong type of object.', name: 'UnknownErrorException', details: 'FormatError: Page dictionary kid reference points to wrong type of object.', stack: 'Error\n    at BaseExceptionClosure (https://sredisn…i/indigo/lib/pdf/pdfjs/3.11.174/build/pdf.js:32:3'}
details
: 
"FormatError: Page dictionary kid reference points to wrong type of object."
message
: 
"Page dictionary kid reference points to wrong type of object."
name
: 
"UnknownErrorException"
stack
: 
"Error\n    at BaseExceptionClosure (https://sredisnjikatalogrh.gov.hr/doki/indigo/lib/pdf/pdfjs/3.11.174/build/pdf.js:446:29)\n    at Object.defineProperty.value (https://sredisnjikatalogrh.gov.hr/doki/indigo/lib/pdf/pdfjs/3.11.174/build/pdf.js:449:2)\n    at __w_pdfjs_require__ (https://sredisnjikatalogrh.gov.hr/doki/indigo/lib/pdf/pdfjs/3.11.174/build/pdf.js:17849:41)\n    at https://sredisnjikatalogrh.gov.hr/doki/indigo/lib/pdf/pdfjs/3.11.174/build/pdf.js:18129:13\n    at https://sredisnjikatalogrh.gov.hr/doki/indigo/lib/pdf/pdfjs/3.11.174/build/pdf.js:18140:3\n    at https://sredisnjikatalogrh.gov.hr/doki/indigo/lib/pdf/pdfjs/3.11.174/build/pdf.js:18143:12\n    at webpackUniversalModuleDefinition (https://sredisnjikatalogrh.gov.hr/doki/indigo/lib/pdf/pdfjs/3.11.174/build/pdf.js:31:50)\n    at https://sredisnjikatalogrh.gov.hr/doki/indigo/lib/pdf/pdfjs/3.11.174/build/pdf.js:32:3"
[[Prototype]]
: 
Error
(anonymous)	@	pdf_viewer.js:1018
Promise.catch (async)		
setDocument	@	pdf_viewer.js:833
load	@	app.js:1323
loadingTask.promise.then.key	@	app.js:1113
Promise.then (async)		
open	@	app.js:1111
run	@	app.js:787
await in run (async)		
webViewerLoad	@	viewer.js:21
```

![image](https://github.com/mozilla/pdf.js/assets/4988133/05ce3b92-c85c-48e3-8951-436fb2283c9b)

![image](https://github.com/mozilla/pdf.js/assets/4988133/b7203a58-0c3a-4375-967d-b9b917f584af)

**Comment by Snuffleupagus** [comment]
> I don't know if this is fixable but a similar bug has been solved before so ...

Please keep in mind that just because the issues *look similar* on the outside, that unfortunately doesn't mean that the underlying problem is connected when it comes to corrupt PDF documents.

> Attach (recommended) or Link to PDF file here:
> I can provide such PDF via private channel.

Unfortunately that's a problem, since all patches are *required* to include a test-case and it's usually really really difficult to manually create a PDF document that's corrupt in the "right" way.

Given that above, let's close this for now since it's not really actionable as-is.

**Comment by hrvoj3e** [comment]
Hi. Client has allowed to share the pdf file.
Could you take a look now?

[broken-pdf-pdfjs.pdf](https://github.com/mozilla/pdf.js/files/13161996/broken-pdf-pdfjs.pdf)

**Comment by themegabyte** [comment]
Seeing the same error from PDF files saved with Foxit reader. Any luck in fixing this? @hrvoj3e ? @Snuffleupagus you do have a test case now attached here: https://github.com/mozilla/pdf.js/issues/17163#issuecomment-1778585863

**Comment by illfygli** [comment]
For what it's worth, the linked PDF file has references to pages that don't exist in the file.

If I remove `3 0 R 4 0 R 5 0 R 6 0 R`, none of which exist, it opens in PDF.js for me.

(Ended up here because I'm making a PDF generator and accidentally generated a broken one.)
