### ISSUE TITLE
npm install fails on Mac Mini M2

### ISSUE THREAD

**Issue by clintonblackmore** [mozilla/pdf.js#17178]
I'm trying to follow the instructions for [getting the code](https://github.com/mozilla/pdf.js#getting-the-code). Getting the repo from git and installing gulp both work fine. When I try to do `npm install`, it fails.

~~Attach (recommended) or Link to PDF file here:~~ (not applicable)

Configuration:

I'm using a Mac mini (2023), aka Mac14,3 with an Apple M2 chip and 8 GB of RAM. I'm running macOS Ventura 13.5.2. I'm using Node v21.1.0 (npm 10.2.0). [I installed it with [nvm for the fish shell](https://github.com/jorgebucaran/nvm.fish). I also tried node v18.17.1].

I am on the master branch and got the latest from git tonight. The last changeset is:

```
commit fbfacf8828eddd0c458a330f162c5a3f7f5dc948 (HEAD -> master, origin/master, origin/HEAD)
Merge: b31e77df1 399f444c8
Author: calixteman <calixte.denizet@gmail.com>
Date:   Wed Oct 25 21:46:49 2023 +0200

    Merge pull request #17177 from Snuffleupagus/xfaLayer-pause-l10n
    
    Pause translation when appending the xfaLayer to the page
```

Steps to reproduce the problem.
1. Follow the getting started instructions.
2. Run `npm install` when instructed.

What is the expected behaviour?

The dependancies should install.

What went wrong?

When I try `npm install` it fails with lots of different errors. It looks like it can't build binaries or download required dependancies for the architecture.

<img width="1495" alt="Screenshot 2023-10-25 at 7 32 16 PM" src="https://github.com/mozilla/pdf.js/assets/64144/89ce147f-6e5b-402a-89bf-4234daaff9e6">

Here is the output in text form:

```
clinton@Clintons-Mini ~/P/L/pdf.js (master)> npm install
npm WARN skipping integrity check for git dependency ssh://git@github.com/mozfreddyb/eslint-plugin-sdl.git 
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated mkdirp@0.5.4: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: The v1 package contains DANGEROUS / INSECURE binaries. Upgrade to safe fsevents v2
npm WARN deprecated mkdirp@0.3.5: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated highlight.js@9.18.5: Support has ended for 9.x series. Upgrade to @latest
npm WARN deprecated core-js@2.6.9: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! path /Users/clinton/Projects/Learning/pdf.js/node_modules/canvas
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build --update-binary
npm ERR! Failed to execute '/Users/clinton/.local/share/nvm/v21.1.0/bin/node /Users/clinton/.local/share/nvm/v21.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/Users/clinton/Projects/Learning/pdf.js/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/clinton/Projects/Learning/pdf.js/node_modules/canvas/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v120' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.5
npm ERR! node-pre-gyp info using node@21.1.0 | darwin | arm64
npm ERR! (node:50636) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v120-darwin-unknown-arm64.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v120-darwin-unknown-arm64.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.11.2 and node@21.1.0 (node-v120 ABI, unknown) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v120-darwin-unknown-arm64.tar.gz 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.4.0
npm ERR! gyp info using node@21.1.0 | darwin | arm64
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.4.0
npm ERR! gyp info using node@21.1.0 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.9.6 found at "/Library/Developer/CommandLineTools/usr/bin/python3"
npm ERR! gyp info spawn /Library/Developer/CommandLineTools/usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/clinton/.local/share/nvm/v21.1.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/clinton/Projects/Learning/pdf.js/node_modules/canvas/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/clinton/.local/share/nvm/v21.1.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/clinton/Library/Caches/node-gyp/21.1.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/clinton/Library/Caches/node-gyp/21.1.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/clinton/.local/share/nvm/v21.1.0/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/clinton/Library/Caches/node-gyp/21.1.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/clinton/Projects/Learning/pdf.js/node_modules/canvas',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! /bin/sh: pkg-config: command not found
npm ERR! gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/Users/clinton/.local/share/nvm/v21.1.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:325:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:515:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
npm ERR! gyp ERR! System Darwin 22.6.0
npm ERR! gyp ERR! command "/Users/clinton/.local/share/nvm/v21.1.0/bin/node" "/Users/clinton/.local/share/nvm/v21.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--update-binary" "--module=/Users/clinton/Projects/Learning/pdf.js/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/Users/clinton/Projects/Learning/pdf.js/node_modules/canvas/build/Release" "--napi_version=9" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v120"
npm ERR! gyp ERR! cwd /Users/clinton/Projects/Learning/pdf.js/node_modules/canvas
npm ERR! gyp ERR! node -v v21.1.0
npm ERR! gyp ERR! node-gyp -v v9.4.0
npm ERR! gyp ERR! not ok 
npm ERR! node-pre-gyp ERR! build error 
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/Users/clinton/.local/share/nvm/v21.1.0/bin/node /Users/clinton/.local/share/nvm/v21.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/Users/clinton/Projects/Learning/pdf.js/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/clinton/Projects/Learning/pdf.js/node_modules/canvas/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v120' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/clinton/Projects/Learning/pdf.js/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:515:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
npm ERR! node-pre-gyp ERR! System Darwin 22.6.0
npm ERR! node-pre-gyp ERR! command "/Users/clinton/.local/share/nvm/v21.1.0/bin/node" "/Users/clinton/Projects/Learning/pdf.js/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--update-binary"
npm ERR! node-pre-gyp ERR! cwd /Users/clinton/Projects/Learning/pdf.js/node_modules/canvas
npm ERR! node-pre-gyp ERR! node -v v21.1.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.5
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in: /Users/clinton/.npm/_logs/2023-10-26T01_26_08_547Z-debug-0.log
clinton@Clintons-Mini ~/P/L/pdf.js (master) [1]> 
```

~~Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):~~ (not applicable)

**Comment by Snuffleupagus** [comment]
This looks like an issue with the `node-canvas` package, which we unfortunately cannot provide all that much help with here, please refer to e.g. https://github.com/Automattic/node-canvas/issues/1684 and https://github.com/Automattic/node-canvas#compiling
