### ISSUE TITLE
Reboot the Windows bot

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#18071]
It looks like the Windows bot has crashed. We've seen timeouts of 60 minutes in e.g. #18052 and shortly after the bot didn't respond to commands anymore.

@calixteman Could you perhaps check what happened and reboot it, since not having the bot available is currently blocking some PRs?

**Comment by calixteman** [comment]
I restarted the bot this morning (around 8:30 UTC+0).

**Comment by timvandermeij** [comment]
@calixteman Sadly it looks like the Windows bot is down again; see the final comments at https://github.com/mozilla/pdf.js/pull/17923. It's strange because the first run failed pretty quickly with what looks like a Git clone timeout and after that a run took over an hour and the logs don't load anymore...

**Comment by calixteman** [comment]
I just restart the bot.
The error was (the same as the one from this morning):
```
Error: EPERM: operation not permitted, unlink 'C:\pdfjs\botio-files-pdfjs\private\3ad9ebab6ed3957/node_modules/npm/node_modules/node-gyp/gyp/tools/pretty_sln.py'
    at Object.unlinkSync (node:fs:1808:3)
    at _unlinkSync (C:\Users\Administrator\AppData\Roaming\npm\node_modules\botio\node_modules\shelljs\shell.js:1398:10)
    at rmdirSyncRecursive (C:\Users\Administrator\AppData\Roaming\npm\node_modules\botio\node_modules\shelljs\shell.js:1145:9)
    at rmdirSyncRecursive (C:\Users\Administrator\AppData\Roaming\npm\node_modules\botio\node_modules\shelljs\shell.js:1135:7)
    at rmdirSyncRecursive (C:\Users\Administrator\AppData\Roaming\npm\node_modules\botio\node_modules\shelljs\shell.js:1135:7)
    at rmdirSyncRecursive (C:\Users\Administrator\AppData\Roaming\npm\node_modules\botio\node_modules\shelljs\shell.js:1135:7)
    at rmdirSyncRecursive (C:\Users\Administrator\AppData\Roaming\npm\node_modules\botio\node_modules\shelljs\shell.js:1135:7)
    at rmdirSyncRecursive (C:\Users\Administrator\AppData\Roaming\npm\node_modules\botio\node_modules\shelljs\shell.js:1135:7)
    at rmdirSyncRecursive (C:\Users\Administrator\AppData\Roaming\npm\node_modules\botio\node_modules\shelljs\shell.js:1135:7)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\botio\node_modules\shelljs\shell.js:384:7

```

**Comment by timvandermeij** [comment]
It looks like some process got interrupted and left files behind with invalid permissions. In any case, the cleanup seems to have worked now that the Windows bot is functional again. Thank you!
