### ISSUE TITLE
Fix integration tests "Highlight Editor Highlight and caret browsing"

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#18187]
The most recent failures of this suite are in http://54.193.163.58:8877/dab06cb264dae58/output.txt, with the following tracebacks:

```
Failures:
2) Highlight Editor Highlight and caret browsing must check that the caret can move a highlighted text
  Message:
[31m    TypeError: Cannot read properties of undefined (reading 'reset')[0m
  Stack:
        at evaluate (evaluate at UserContext.<anonymous> (file:///C:/pdfjs/botio-files-pdfjs/private/dab06cb264dae58/test/integration/highlight_editor_spec.mjs:1017:20), <anonymous>:1:27)
        at #evaluate (file:///C:/pdfjs/botio-files-pdfjs/private/dab06cb264dae58/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/ExecutionContext.js:373:19)
        at async ExecutionContext.evaluate (file:///C:/pdfjs/botio-files-pdfjs/private/dab06cb264dae58/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/ExecutionContext.js:268:16)
        at async IsolatedWorld.evaluate (file:///C:/pdfjs/botio-files-pdfjs/private/dab06cb264dae58/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/IsolatedWorld.js:96:16)
        at async CdpFrame.evaluate (file:///C:/pdfjs/botio-files-pdfjs/private/dab06cb264dae58/node_modules/puppeteer-core/lib/esm/puppeteer/api/Frame.js:339:20)
        at async CdpPage.evaluate (file:///C:/pdfjs/botio-files-pdfjs/private/dab06cb264dae58/node_modules/puppeteer-core/lib/esm/puppeteer/api/Page.js:796:20)
        at async UserContext.<anonymous> (file:///C:/pdfjs/botio-files-pdfjs/private/dab06cb264dae58/test/integration/highlight_editor_spec.mjs:1017:9)

3) Highlight Editor Highlight and caret browsing must check that selection is correctly highlighted on arrow down key pressed
  Message:
[31m    ProtocolError: Waiting for selector `.annotationEditorLayer.highlightEditing` failed: Runtime.callFunctionOn timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.[0m
  Stack:
        at <instance_members_initializer> (file:///C:/pdfjs/botio-files-pdfjs/private/dab06cb264dae58/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:89:14)
        at new Callback (file:///C:/pdfjs/botio-files-pdfjs/private/dab06cb264dae58/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:93:16)
        at CallbackRegistry.create (file:///C:/pdfjs/botio-files-pdfjs/private/dab06cb264dae58/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:19:26)
        at Connection._rawSend (file:///C:/pdfjs/botio-files-pdfjs/private/dab06cb264dae58/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:85:26)
        at CdpCDPSession.send (file:///C:/pdfjs/botio-files-pdfjs/private/dab06cb264dae58/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/CDPSession.js:63:33)
        at #evaluate (file:///C:/pdfjs/botio-files-pdfjs/private/dab06cb264dae58/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/ExecutionContext.js:353:50)
        at async ExecutionContext.evaluateHandle (file:///C:/pdfjs/botio-files-pdfjs/private/dab06cb264dae58/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/ExecutionContext.js:320:16)
        at async IsolatedWorld.evaluateHandle (file:///C:/pdfjs/botio-files-pdfjs/private/dab06cb264dae58/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/IsolatedWorld.js:85:16)
        at async CdpJSHandle.evaluateHandle (file:///C:/pdfjs/botio-files-pdfjs/private/dab06cb264dae58/node_modules/puppeteer-core/lib/esm/puppeteer/api/JSHandle.js:147:20)
        at async WaitTask.rerun (file:///C:/pdfjs/botio-files-pdfjs/private/dab06cb264dae58/node_modules/puppeteer-core/lib/esm/puppeteer/common/WaitTask.js:100:28)
  Message:
[31m    TypeError: Cannot read properties of undefined (reading 'reset')[0m
  Stack:
        at evaluate (evaluate at UserContext.<anonymous> (file:///C:/pdfjs/botio-files-pdfjs/private/dab06cb264dae58/test/integration/highlight_editor_spec.mjs:1017:20), <anonymous>:1:27)
        at #evaluate (file:///C:/pdfjs/botio-files-pdfjs/private/dab06cb264dae58/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/ExecutionContext.js:373:19)
        at async ExecutionContext.evaluate (file:///C:/pdfjs/botio-files-pdfjs/private/dab06cb264dae58/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/ExecutionContext.js:268:16)
        at async IsolatedWorld.evaluate (file:///C:/pdfjs/botio-files-pdfjs/private/dab06cb264dae58/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/IsolatedWorld.js:96:16)
        at async CdpFrame.evaluate (file:///C:/pdfjs/botio-files-pdfjs/private/dab06cb264dae58/node_modules/puppeteer-core/lib/esm/puppeteer/api/Frame.js:339:20)
        at async CdpPage.evaluate (file:///C:/pdfjs/botio-files-pdfjs/private/dab06cb264dae58/node_modules/puppeteer-core/lib/esm/puppeteer/api/Page.js:796:20)
        at async UserContext.<anonymous> (file:///C:/pdfjs/botio-files-pdfjs/private/dab06cb264dae58/test/integration/highlight_editor_spec.mjs:1017:9)

4) Highlight Editor Highlight and caret browsing must check that an highlight can be left with the keyboard
  Message:
[31m    TypeError: Cannot read properties of undefined (reading 'reset')[0m
  Stack:
        at evaluate (evaluate at UserContext.<anonymous> (file:///C:/pdfjs/botio-files-pdfjs/private/dab06cb264dae58/test/integration/highlight_editor_spec.mjs:1017:20), <anonymous>:1:27)
        at #evaluate (file:///C:/pdfjs/botio-files-pdfjs/private/dab06cb264dae58/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/ExecutionContext.js:373:19)
        at async ExecutionContext.evaluate (file:///C:/pdfjs/botio-files-pdfjs/private/dab06cb264dae58/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/ExecutionContext.js:268:16)
        at async IsolatedWorld.evaluate (file:///C:/pdfjs/botio-files-pdfjs/private/dab06cb264dae58/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/IsolatedWorld.js:96:16)
        at async CdpFrame.evaluate (file:///C:/pdfjs/botio-files-pdfjs/private/dab06cb264dae58/node_modules/puppeteer-core/lib/esm/puppeteer/api/Frame.js:339:20)
        at async CdpPage.evaluate (file:///C:/pdfjs/botio-files-pdfjs/private/dab06cb264dae58/node_modules/puppeteer-core/lib/esm/puppeteer/api/Page.js:796:20)
        at async UserContext.<anonymous> (file:///C:/pdfjs/botio-files-pdfjs/private/dab06cb264dae58/test/integration/highlight_editor_spec.mjs:1017:9)
```

It looks like this fails because the `annotationeditoruimanager` event is listened for too late, causing `window.uiManager` not to be set in `beforeAll` (see https://github.com/mozilla/pdf.js/blob/master/test/integration/highlight_editor_spec.mjs#L1003). This causes all tests in the suite to fail in the cleanup step in `afterEach` (see https://github.com/mozilla/pdf.js/blob/master/test/integration/highlight_editor_spec.mjs#L1018) because that assumes that `window.uiManager`  is defined. Note that we don't want to use `window.uiManager?.reset()` because even though that'd make cleanup pass it'd be wallpapering over the actual issue of `window.uiManager` being undefined.

We should probably find a way to register event listeners earlier, so before the entire viewer is initialized and the PDF document is set (so slightly before the `initializationPromise` is resolved). For this a first version is made in #17709 but we should see if there is an easier way to achieve this.

**Comment by timvandermeij** [comment]
Closing since this is fixed by #18574.
