### ISSUE TITLE
[Bug]: Building PDF.js instructions from README does not workf or me

### ISSUE THREAD

**Issue by catmanjan** [mozilla/pdf.js#18519]
### Attach (recommended) or Link to PDF file

n/a

### Web browser and its version

Google Chrome

### Operating system and its version

Windows 11

### PDF.js version

master

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

I did a fresh clone and ran the following commands:

npm install
npx gulp generic

### What is the expected behavior?

Builds

### What went wrong?

```
PS C:\Users\sysadmin\source\repos\pdf.js> npm install
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@3. I'll try to do my best with it!
npm WARN deprecated @jazzer.js/core@2.1.0: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated @humanwhocodes/config-array@0.11.14: Use @eslint/config-array instead in 1582ms
npm WARN deprecated @jazzer.js/fuzzer@2.1.0: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated @jazzer.js/bug-detectors@2.1.0: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated @jazzer.js/instrumentor@2.1.0: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated @jazzer.js/hooking@2.1.0: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead

> @jazzer.js/fuzzer@2.1.0 install C:\Users\sysadmin\source\repos\pdf.js\node_modules\@jazzer.js\fuzzer
> prebuild-install --runtime napi || npm run prebuild


> canvas@2.11.2 install C:\Users\sysadmin\source\repos\pdf.js\node_modules\canvas
> node-pre-gyp install --fallback-to-build --update-binary

[canvas] Success: "C:\Users\sysadmin\source\repos\pdf.js\node_modules\canvas\build\Release\canvas.node" is installed via remote

> core-js@3.37.1 postinstall C:\Users\sysadmin\source\repos\pdf.js\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting core-js:
> https://opencollective.com/core-js
> https://patreon.com/zloirock
> https://boosty.to/zloirock
> bitcoin: bc1qlea7544qtsmj2rayg0lthvza9fau63ux0fstcz

I highly recommend reading this: https://github.com/zloirock/core-js/blob/master/docs/2023-02-14-so-whats-next.md


> metalsmith@2.6.3 postinstall C:\Users\sysadmin\source\repos\pdf.js\node_modules\metalsmith
> node metalsmith-migrated-plugins.js || exit 0


> puppeteer@22.14.0 postinstall C:\Users\sysadmin\source\repos\pdf.js\node_modules\puppeteer
> node install.mjs

Skipping browser installation because the Puppeteer build is not available. Run `npm install` again after you have re-built Puppeteer.

> pdf.js@ postinstall C:\Users\sysadmin\source\repos\pdf.js
> cross-env PUPPETEER_PRODUCT=firefox node node_modules/puppeteer/install.mjs

Skipping browser installation because the Puppeteer build is not available. Run `npm install` again after you have re-built Puppeteer.
npm WARN notsup Unsupported engine for @jazzer.js/core@2.1.0: wanted: {"node":">= 14.0.0","npm":">= 7.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @jazzer.js/core@2.1.0
npm WARN notsup Unsupported engine for @fluent/bundle@0.18.0: wanted: {"node":">=14.0.0","npm":">=7.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @fluent/bundle@0.18.0
npm WARN notsup Unsupported engine for @fluent/dom@0.10.0: wanted: {"node":">=18.0.0","npm":">=7.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @fluent/dom@0.10.0
npm WARN notsup Unsupported engine for eslint-plugin-html@8.1.1: wanted: {"node":">=16.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: eslint-plugin-html@8.1.1
npm WARN notsup Unsupported engine for eslint-plugin-unicorn@55.0.0: wanted: {"node":">=18.18"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: eslint-plugin-unicorn@55.0.0
npm WARN notsup Unsupported engine for gulp-postcss@10.0.0: wanted: {"node":">=18"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: gulp-postcss@10.0.0
npm WARN notsup Unsupported engine for gulp-zip@6.0.0: wanted: {"node":">=18"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: gulp-zip@6.0.0
npm WARN notsup Unsupported engine for postcss-dark-theme-class@1.3.0: wanted: {"node":">=18.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: postcss-dark-theme-class@1.3.0
npm WARN notsup Unsupported engine for postcss-discard-comments@7.0.1: wanted: {"node":"^18.12.0 || ^20.9.0 || >=22.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: postcss-discard-comments@7.0.1
npm WARN notsup Unsupported engine for puppeteer@22.14.0: wanted: {"node":">=18"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: puppeteer@22.14.0
npm WARN notsup Unsupported engine for stylelint@16.8.1: wanted: {"node":">=18.12.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: stylelint@16.8.1npm WARN notsup Unsupported engine for stylelint-prettier@5.0.2: wanted: {"node":">=18.12.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: stylelint-prettier@5.0.2
npm WARN notsup Unsupported engine for @jazzer.js/bug-detectors@2.1.0: wanted: {"node":">= 14.0.0","npm":">= 7.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @jazzer.js/bug-detectors@2.1.0
npm WARN notsup Unsupported engine for @jazzer.js/hooking@2.1.0: wanted: {"node":">= 14.0.0","npm":">= 7.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})npm WARN notsup Not compatible with your version of node/npm: @jazzer.js/hooking@2.1.0
npm WARN notsup Unsupported engine for @jazzer.js/instrumentor@2.1.0: wanted: {"node":">= 14.0.0","npm":">= 7.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @jazzer.js/instrumentor@2.1.0
npm WARN notsup Unsupported engine for @jazzer.js/fuzzer@2.1.0: wanted: {"node":">= 14.0.0","npm":">= 7.0.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @jazzer.js/fuzzer@2.1.0
npm WARN notsup Unsupported engine for globals@15.8.0: wanted: {"node":">=18"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: globals@15.8.0
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN notsup Unsupported engine for postcss-load-config@5.1.0: wanted: {"node":">= 18"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: postcss-load-config@5.1.0
npm WARN notsup Unsupported engine for get-stream@8.0.1: wanted: {"node":">=16"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: get-stream@8.0.1npm WARN notsup Unsupported engine for gulp-plugin-extras@0.3.0: wanted: {"node":">=18"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: gulp-plugin-extras@0.3.0
npm WARN notsup Unsupported engine for puppeteer-core@22.14.0: wanted: {"node":">=18"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: puppeteer-core@22.14.0
npm WARN notsup Unsupported engine for @puppeteer/browsers@2.3.0: wanted: {"node":">=18"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: @puppeteer/browsers@2.3.0
npm WARN notsup Unsupported engine for file-entry-cache@9.0.0: wanted: {"node":">=18"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: file-entry-cache@9.0.0
npm WARN notsup Unsupported engine for meow@13.2.0: wanted: {"node":">=18"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: meow@13.2.0
npm WARN notsup Unsupported engine for postcss-safe-parser@7.0.0: wanted: {"node":">=18.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: postcss-safe-parser@7.0.0
npm WARN notsup Unsupported engine for flat-cache@5.0.0: wanted: {"node":">=18"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: flat-cache@5.0.0npm WARN eslint-plugin-mozilla@3.7.4 requires a peer of @microsoft/eslint-plugin-sdl@^0.2.2 but none is installed. You must install peer dependencies yourself.

added 1015 packages from 695 contributors and audited 1021 packages in 61.544s
194 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

PS C:\Users\sysadmin\source\repos\pdf.js> npx gulp generic
[10:59:08] Using gulpfile ~\source\repos\pdf.js\gulpfile.mjs
[10:59:08] Starting 'generic'...
[10:59:08] Starting 'createBuildNumber'...

### Getting extension build number
Extension build number: 159
[10:59:09] Finished 'createBuildNumber' after 232 ms
[10:59:09] Starting 'locale'...

### Building localization files
[10:59:09] Finished 'locale' after 220 ms
[10:59:09] Starting 'scriptingGeneric'...

### Building default preferences
[10:59:09] assets by status 7.22 KiB [cached] 1 asset


ERROR in ./web/app_options.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: C:\Users\sysadmin\source\repos\pdf.js\web\app_options.js: body.at is not a function
    at PluginPass.exit (file:///C:/Users/sysadmin/source/repos/pdf.js/external/builder/babel-plugin-pdfjs-preprocessor.mjs:230:38)
    at newFn (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\visitors.js:162:14)
    at NodePath._call (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\path\context.js:49:20)
    at NodePath.call (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\path\context.js:39:18)
    at NodePath.visit (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\path\context.js:93:8)
    at TraversalContext.visitQueue (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\context.js:89:16)
    at TraversalContext.visitSingle (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\context.js:65:19)
    at TraversalContext.visit (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\context.js:112:19)
    at traverseNode (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\traverse-node.js:22:17)
    at NodePath.visit (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\path\context.js:91:52)
    at TraversalContext.visitQueue (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\context.js:89:16)
    at TraversalContext.visitSingle (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\context.js:65:19)
    at TraversalContext.visit (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\context.js:112:19)
    at traverseNode (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\traverse-node.js:22:17)
    at NodePath.visit (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\path\context.js:91:52)
    at TraversalContext.visitQueue (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\context.js:89:16)
    at TraversalContext.visitMultiple (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\context.js:61:17)
    at TraversalContext.visit (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\context.js:110:19)
    at traverseNode (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\traverse-node.js:22:17)
    at NodePath.visit (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\path\context.js:91:52)
    at TraversalContext.visitQueue (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\context.js:89:16)
    at TraversalContext.visitSingle (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\context.js:65:19)
    at TraversalContext.visit (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\context.js:112:19)
    at traverseNode (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\traverse-node.js:22:17)
    at NodePath.visit (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\path\context.js:91:52)
    at TraversalContext.visitQueue (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\context.js:89:16)
    at TraversalContext.visitMultiple (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\context.js:61:17)
    at TraversalContext.visit (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\context.js:110:19)
    at traverseNode (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\traverse-node.js:22:17)
    at NodePath.visit (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\path\context.js:91:52)
    at TraversalContext.visitQueue (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\context.js:89:16)
    at TraversalContext.visitSingle (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\context.js:65:19)
    at TraversalContext.visit (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\context.js:112:19)
    at traverseNode (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\traverse-node.js:22:17)
    at traverse (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\index.js:53:34)
    at transformFile (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\core\lib\transformation\index.js:82:31)
    at transformFile.next (<anonymous>)
    at run (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\core\lib\transformation\index.js:24:12)
    at run.next (<anonymous>)
    at transform (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\core\lib\transform.js:22:33)
    at transform.next (<anonymous>)
    at step (C:\Users\sysadmin\source\repos\pdf.js\node_modules\gensync\index.js:261:32)
    at C:\Users\sysadmin\source\repos\pdf.js\node_modules\gensync\index.js:273:13
    at async.call.result.err.err (C:\Users\sysadmin\source\repos\pdf.js\node_modules\gensync\index.js:223:11)
    at C:\Users\sysadmin\source\repos\pdf.js\node_modules\gensync\index.js:189:28
    at C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\core\lib\gensync-utils\async.js:67:7
    at C:\Users\sysadmin\source\repos\pdf.js\node_modules\gensync\index.js:113:33
    at step (C:\Users\sysadmin\source\repos\pdf.js\node_modules\gensync\index.js:287:14)
    at C:\Users\sysadmin\source\repos\pdf.js\node_modules\gensync\index.js:273:13
    at async.call.result.err.err (C:\Users\sysadmin\source\repos\pdf.js\node_modules\gensync\index.js:223:11)

webpack 5.93.0 compiled with 1 error
[10:59:10] assets by status 6.87 KiB [cached] 1 asset


ERROR in ./src/scripting_api/initialization.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: C:\Users\sysadmin\source\repos\pdf.js\src\scripting_api\initialization.js: body.at is not a function
    at PluginPass.exit (file:///C:/Users/sysadmin/source/repos/pdf.js/external/builder/babel-plugin-pdfjs-preprocessor.mjs:230:38)
    at newFn (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\visitors.js:162:14)
    at NodePath._call (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\path\context.js:49:20)
    at NodePath.call (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\path\context.js:39:18)
    at NodePath.visit (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\path\context.js:93:8)
    at TraversalContext.visitQueue (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\context.js:89:16)
    at TraversalContext.visitSingle (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\context.js:65:19)
    at TraversalContext.visit (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\context.js:112:19)
    at traverseNode (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\traverse-node.js:22:17)
    at NodePath.visit (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\path\context.js:91:52)
    at TraversalContext.visitQueue (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\context.js:89:16)
    at TraversalContext.visitMultiple (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\context.js:61:17)
    at TraversalContext.visit (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\context.js:110:19)
    at traverseNode (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\traverse-node.js:22:17)
    at NodePath.visit (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\path\context.js:91:52)
    at TraversalContext.visitQueue (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\context.js:89:16)
    at TraversalContext.visitSingle (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\context.js:65:19)
    at TraversalContext.visit (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\context.js:112:19)
    at traverseNode (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\traverse-node.js:22:17)
    at NodePath.visit (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\path\context.js:91:52)
    at TraversalContext.visitQueue (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\context.js:89:16)
    at TraversalContext.visitMultiple (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\context.js:61:17)
    at TraversalContext.visit (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\context.js:110:19)
    at traverseNode (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\traverse-node.js:22:17)
    at NodePath.visit (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\path\context.js:91:52)
    at TraversalContext.visitQueue (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\context.js:89:16)
    at TraversalContext.visitSingle (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\context.js:65:19)
    at TraversalContext.visit (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\context.js:112:19)
    at traverseNode (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\traverse-node.js:22:17)
    at traverse (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\traverse\lib\index.js:53:34)
    at transformFile (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\core\lib\transformation\index.js:82:31)
    at transformFile.next (<anonymous>)
    at run (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\core\lib\transformation\index.js:24:12)
    at run.next (<anonymous>)
    at transform (C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\core\lib\transform.js:22:33)
    at transform.next (<anonymous>)
    at step (C:\Users\sysadmin\source\repos\pdf.js\node_modules\gensync\index.js:261:32)
    at C:\Users\sysadmin\source\repos\pdf.js\node_modules\gensync\index.js:273:13
    at async.call.result.err.err (C:\Users\sysadmin\source\repos\pdf.js\node_modules\gensync\index.js:223:11)
    at C:\Users\sysadmin\source\repos\pdf.js\node_modules\gensync\index.js:189:28
    at C:\Users\sysadmin\source\repos\pdf.js\node_modules\@babel\core\lib\gensync-utils\async.js:67:7
    at C:\Users\sysadmin\source\repos\pdf.js\node_modules\gensync\index.js:113:33
    at step (C:\Users\sysadmin\source\repos\pdf.js\node_modules\gensync\index.js:287:14)
    at C:\Users\sysadmin\source\repos\pdf.js\node_modules\gensync\index.js:273:13
    at async.call.result.err.err (C:\Users\sysadmin\source\repos\pdf.js\node_modules\gensync\index.js:223:11)
    at C:\Users\sysadmin\source\repos\pdf.js\node_modules\gensync\index.js:37:40
 @ ./src/pdf.scripting.js 1:0-64 5:2-13

webpack 5.93.0 compiled with 1 error
[10:59:10] The following tasks did not complete: generic, scriptingGeneric
Did you forget to signal async completion?
PS C:\Users\sysadmin\source\repos\pdf.js>
```

**Comment by catmanjan** [comment]
Updated nodejs and fixed it!
