### ISSUE TITLE
Fix the "Text selection using selection carets doesn't jump when moving selection" integration test

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#18857]
This integration test fails consistently on _only_ the Windows bot with the following traceback (see http://54.193.163.58:8877/a50e80772f15bca/output.txt):

```
Failures:
1) Text layer Text selection using selection carets doesn't jump when moving selection
  Message:
[31m    second selection:
        Expected 'frequently executed) bytecode sequences, records
        them, and compiles them to fast native code. We call such a s' to roughly match /frequently .* We call such a se/s.[0m
  Stack:
        at <Jasmine>
        at UserContext.<anonymous> (file:///C:/pdfjs/botio-files-pdfjs/private/a50e80772f15bca/test/integration/text_layer_spec.mjs:421:12)
  Message:
[31m    third selection:
        Expected 'frequently executed) bytecode sequences, records
        them, and compiles them to fast native code. We call such a s' to roughly match /frequently .* We call such a se/s.[0m
  Stack:
        at <Jasmine>
        at UserContext.<anonymous> (file:///C:/pdfjs/botio-files-pdfjs/private/a50e80772f15bca/test/integration/text_layer_spec.mjs:429:12
```

I have seen this one in at least #18851, #18853 and #18855.

**Comment by timvandermeij** [comment]
Closing since this is fixed by #18844. It looks like the problem was the misplacement of the text layer, causing one character not to be selected anymore (which can also be verified with the reference images in that PR).
