### ISSUE TITLE
[Bug]: HC-PDF - Images are loaded in low resolution/quality, making them unreadable

### ISSUE THREAD

**Issue by kgronowski** [mozilla/pdf.js#19049]
### Attach (recommended) or Link to PDF file

https://sbc.org.pl/Content/874002/PDF/BŚ-RIII6831-1921.pdf

### Web browser and its version

Chrome 131.0.6778.70 / Firefox 132.0.2

### Operating system and its version

Windows 10/11

### PDF.js version

4.0.269 and latest

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. Open linked PDF file in viewer or directly in Firefox or go to https://sbc.org.pl/formats/pdf/web/viewer.html?file=https%3A%2F%2Fsbc.org.pl%2FContent%2F874002%2FPDF%2FB%25C5%259A-RIII6831-1921.pdf

### What is the expected behavior?

Images are rendered in high resolution/quality, texts are readable. Just like in default PDF viewer in chromium based browsers or Adobe Acrobat.
![image](https://github.com/user-attachments/assets/e3122b03-8fd8-47bb-babe-db207af1c141)

### What went wrong?

Images are loaded in low resolution/quality.

![image](https://github.com/user-attachments/assets/183999e7-a41a-418b-9d21-4867635b5ae2)

### Link to a viewer

https://sbc.org.pl/formats/pdf/web/viewer.html?file=https%3A%2F%2Fsbc.org.pl%2FContent%2F874002%2FPDF%2FB%25C5%259A-RIII6831-1921.pdf

### Additional context

Problem could be related to sizes of underlying images as other, smaller PDFs created with the same method render just fine.
Example: https://sbc.org.pl/formats/pdf/web/viewer.html?file=https%3A%2F%2Fsbc.org.pl%2FContent%2F849032%2FPDF%2FB%25C5%259A-BTLw3193-1901.pdf

**Comment by Snuffleupagus** [comment]
Note that each page consists of two separate images, one used as "background" respectively "foreground", and it's the "foreground" images that fail to load.
Hence this isn't technically accurate to say that the quality is bad, since this is what the "background" images look like, but the actual bug is that the "foreground" images are somehow broken and thus fail to render.

**Comment by kgronowski** [comment]
Hey, thanks for your reply. I've updated the issue accordingly.
Do you have any idea what we can do to make image loading work like in other viewers?

**Comment by mmatela** [comment]
@Snuffleupagus Are you sure the `pdf-broken` label is not applied here incorrectly (which would probably decrease the bug's priority)? Is there a reason to believe that something is wrong with the pdf contents?

Adding the error stack in case someone else has a similar error and is searching for keywords:

```
 Maximum call stack size exceeded
 RangeError: Maximum call stack size exceeded
    at SimpleSegmentVisitor.onSymbolDictionary (https://sbc.org.pl/formats/pdf/build/pdf.worker.mjs:9458:22)
    at processSegment (https://sbc.org.pl/formats/pdf/build/pdf.worker.mjs:9359:27)
    at processSegments (https://sbc.org.pl/formats/pdf/build/pdf.worker.mjs:9364:5)
    at parseJbig2Chunks (https://sbc.org.pl/formats/pdf/build/pdf.worker.mjs:9372:5)
    at Jbig2Image.parseChunks (https://sbc.org.pl/formats/pdf/build/pdf.worker.mjs:9956:12)
    at Jbig2Stream.decodeImage (https://sbc.org.pl/formats/pdf/build/pdf.worker.mjs:10007:29)
    at Jbig2Stream.readBlock (https://sbc.org.pl/formats/pdf/build/pdf.worker.mjs:9982:10)
    at Jbig2Stream.getBytes (https://sbc.org.pl/formats/pdf/build/pdf.worker.mjs:3792:14)
    at Jbig2Stream.getImageData (https://sbc.org.pl/formats/pdf/build/pdf.worker.mjs:3812:19)
    at PDFImage.getImageBytes (https://sbc.org.pl/formats/pdf/build/pdf.worker.mjs:31000:41)
```

**Comment by calixteman** [comment]
@mmatela could you attach the pdf to this issue ?

**Comment by mmatela** [comment]
Oh, it actually seems to work correctly in the latest version (5.4.549)
https://mozilla.github.io/pdf.js/web/viewer.html?file=https%3A%2F%2Fsbc.org.pl%2FContent%2F874002%2FPDF%2FB%25C5%259A-RIII6831-1921.pdf

The version built-in in Firefox (5.4.396) still has this problem (or some other one, it prints warnings about TypeErrors rather than RangeErrors).

> [@mmatela](https://github.com/mmatela) could you attach the pdf to this issue ?

It's the same file linked to in the OP. I could attach it, it's in public domain. But it's about 100MB, and I guess it's irrelevant now as this issue can be closed unless I missed something.

**Comment by calixteman** [comment]
I'm attaching the first page in order to have it somewhere (can be useful for archeology purposes):
[First page of BŚ-RIII6831-1921.pdf](https://github.com/user-attachments/files/24496548/First.page.of.BS-RIII6831-1921.pdf)

It has very like been fixed thanks to https://github.com/mozilla/pdf.js/pull/20546.
Anyway if someone wants to fix the issue in our js decoder, it'd be nice, since we use it as a fallback when wasm is disabled.

**Comment by mmatela** [comment]
> It has very like been fixed thanks to [#20546](https://github.com/mozilla/pdf.js/pull/20546).

Except that PR was merged 5 days ago and the latest release was 2 weeks ago :)

**Comment by calixteman** [comment]
The link you mentioned in https://github.com/mozilla/pdf.js/issues/19049#issuecomment-3723941704 is built on master so it has the mentioned patch.
I just checked if it's fixed when falling back on our js decoder and it isn't.
