### ISSUE TITLE
Run the integration tests in a random order

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#19065]
The integration tests currently run in a fixed order, see https://github.com/mozilla/pdf.js/blob/master/test/integration-boot.mjs#L24, which is in contrast with e.g. the unit test that deliberately run in a random order to bring any isolation issues (dependencies between tests) to the surface. Most likely this wasn't done for the integration tests yet because we used to have quite a lot of intermittent issues and dependencies between tests when we started with the integration tests, but over time we have fixed most of them so hopefully running the integration tests in a random order is more feasible nowadays.

We should try this out and make a list of any issues we encounter. This could involve closing the document between tests in the same `describe` block to avoid state leaking through to subsequent tests; see e.g. PR #19064 for which an alternative solution was implemented.

The objective is to reduce the number of test failures (currently if there is a failure in one test it'll currently cause all subsequent dependent tests to fail too) and to improve debugging of the remaining intermittents (currently we sometimes need to run a full `describe` block only to debug one test which is time-consuming).

**Comment by calixteman** [comment]
See https://github.com/mozilla/pdf.js/pull/19064#issuecomment-2481552770.

**Comment by timvandermeij** [comment]
I have tried this out locally today, by closing the document between every test, and that has resulted in a relatively good overview of what needs to be done to achieve the goal of independent tests that can be run in a random order.

There are spec files that already work in random mode, but for example the freetext editor tests are more problematic because there are quite a few tests that build upon the result of the previous test and therefore fail directly if the document is closed between tests. Fortunately this process brings dependencies between _subsequent_ tests to the surface so we can fix them, and from what I can tell enabling random order from that point on should be possible because I haven't found dependencies between _non-subsequent_ tests yet.

This work will roughly involve closing the document between all tests, fixing every failing test and enabling random mode. I have currently investigated, and identified fixes/refactorings for, the following spec files:

| File                                          | Passes if document is closed | Passes if random mode is enabled |
| -------------------------------------- | ----------------------------------------- | -------------------------------------------------- |
| `accessibility_spec.mjs`       | ✅                                                | ✅                                                           |
| `annotation_spec.mjs`         | ✅                                                | ✅                                                           |
| `caret_browsing_spec.mjs` | ✅                                                | ✅                                                           |
| `copy_paste_spec.mjs`        | ✅                                                | ✅                                                           |
| `find_spec.mjs`                     | ✅                                                | ✅                                                           |
| `freetext_editor_spec.mjs` | ❌                                                | ❌                                                           |

**Comment by timvandermeij** [comment]
The freetext integration test failures, when isolated (but not in random mode), are:

<details>
```
Failures:

1) FreeText Editor FreeText must copy/paste
  Message:
    ProtocolError: Waiting for selector `#pdfjs_internal_editor_0` failed: script.callFunction timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.

2) FreeText Editor FreeText must check that a paste has been undone
  Message:
    ProtocolError: Waiting for selector `.annotationEditorLayer` failed: script.callFunction timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.

3) FreeText Editor FreeText must check that aria-owns is correct
  Message:
    ProtocolError: Waiting for selector `#pdfjs_internal_editor_7` failed: Runtime.callFunctionOn timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.

4) FreeText Editor FreeText must check that right click doesn't select
  Message:
    ProtocolError: Waiting for selector `.annotationEditorLayer` failed: Runtime.callFunctionOn timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.

5) FreeText Editor FreeText must check that text change can be undone/redone
  Message:
    ProtocolError: Waiting for selector `.annotationEditorLayer` failed: script.callFunction timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.

6) FreeText Editor Move editor with arrows must check arrow doesn't move an editor when a slider is focused
  Message:
    TypeError: (intermediate value) is not iterable
  Stack:
        at file:///home/timvandermeij/Documenten/Ontwikkeling/pdf.js/Code/test/integration/freetext_editor_spec.mjs:1785:38
        at async Promise.all (index 1)
        at async UserContext.<anonymous> (file:///home/timvandermeij/Documenten/Ontwikkeling/pdf.js/Code/test/integration/freetext_editor_spec.mjs:1780:7)

7) FreeText Editor Move editor with arrows must check the position of an empty freetext
  Message:
    ProtocolError: Waiting for selector `.annotationEditorLayer` failed: Runtime.callFunctionOn timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.

8) FreeText Editor Create editor with keyboard must create an editor with keyboard
  Message:
    ProtocolError: Waiting for selector `#pdfjs_internal_editor_2` failed: Runtime.callFunctionOn timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.
```
