### ISSUE TITLE
Unknown command: callothersubr

### ISSUE THREAD

**Issue by trustbyte** [mozilla/pdf.js#4558]
i believe is similar with this one:
https://github.com/mozilla/pdf.js/issues/1167

the file that https://github.com/andresfcamacho/pdf.js/blob/bug-callothersubr_broken_etrade/test/pdfs/etrade.pdf
I have another file also but i can not share that as it is copyrighted material, but the error is the same.

the error is this:
Uncaught Error: Unknow command: callothersubr pdf.js:475
Error: Unknow command: callothersubr pdf.js:457
    at error (https://xxxx/media/js/pdf.js:473:7)
    at assert (https://xxxx/media/js/pdf.js:489:5)
    at Object.Type1Font_flattenCharstring [as flattenCharstring] (https://xxxxx/media/js/pdf.js:16192:9)
    at Object.Type1Font_getType2Subrs [as getType2Subrs] (https://xxx/media/js/pdf.js:16162:28)
    at Object.Type1Font (https://xxx/media/js/pdf.js:16067:20)
    at Object.Font (https://xxxmedia/js/pdf.js:14159:43)
    at Object.transportObj (https://xxxmedia/js/pdf.js:1329:24)
    at Worker.messageHandlerComObjOnMessage (https://xxx/media/js/pdf.js:27874:19) pdf.js:457
Uncaught Error: Unknow command: callothersubr pdf.js:475
page=1 - getOperatorList: time=261ms, len=3155 pdf.js:27842
Uncaught TypeError: Cannot read property 'data' of undefined 

any hint to make it work?

**Comment by timvandermeij** [comment]
The above patch makes this PDF render just like Adobe Reader/Acrobat. Note that Adobe Reader/Acrobat also complains about this PDF file being damaged, so it is most likely corrupt.
