### ISSUE TITLE
Error reported when rendering pdf

### ISSUE THREAD

**Issue by sethnk** [mozilla/pdf.js#5683]
PDF URL:
http://www.gastrojournal.org/article/S0016-5085(09)00361-8/pdf

Using Windows8.1 x64, Chrome 39 and pdf.js 1.0.1123 (latest)

This PDF reports the following error information when rendering:

PDF.js v1.0.1123 (build: 1b8e44e)
Message: undefined is not a function
Stack: TypeError: undefined is not a function
    at new LinkAnnotation (http://mozilla.github.io/pdf.js/build/pdf.worker.js:5354:29)
    at Function.Annotation_fromRef (http://mozilla.github.io/pdf.js/build/pdf.worker.js:5157:22)
    at Object.annotations (http://mozilla.github.io/pdf.js/build/pdf.worker.js:2838:37)
    at http://mozilla.github.io/pdf.js/build/pdf.worker.js:2480:24
    at LocalPdfManager_ensure [as ensure] (http://mozilla.github.io/pdf.js/build/pdf.worker.js:2478:12)
    at Object.Page_getOperatorList [as getOperatorList] (http://mozilla.github.io/pdf.js/build/pdf.worker.js:2771:43)
    at http://mozilla.github.io/pdf.js/build/pdf.worker.js:34068:14

![image](https://cloud.githubusercontent.com/assets/10129039/5946393/364dc8d0-a72d-11e4-9099-02b7523e4e49.png)

**Comment by timvandermeij** [comment]
The exact location of the problem is `src/core/annotation.js` line 489.

**Comment by timvandermeij** [comment]
@sethnk Thank you for reporting this. I have proposed a fix in #5684.

**Comment by sethnk** [comment]
no problem....  like the project a lot
