### ISSUE TITLE
All browsers, DOMException: Invalid font data in ArrayBuffer

### ISSUE THREAD

**Issue by reggersusa** [mozilla/pdf.js#5798]
link to the PDF: https://www.dropbox.com/s/hd0wvqozfqcvvvy/ContentServer%20%283%29.pdf?dl=0
location in the PDF: page 9
screenshot: none
browser version: Chrome 40.0.2214.111, Safari 8 
operating system: Mac OSX 10.10.2, iOS 8
PDF.js version: 1.0.1175
JavaScript console warning/error messages:
Safari 8/iOS 8:
PDF 316b108488f921409bc02990904f899b [1.6 iTextSharp™ 5.5.4 ©2000-2014 iText Group NV (AGPL-version) / -] (PDF.js: -)
[Error] TypeError: Attempted to assign to readonly property.
	CanvasExtraState_setCurrentPoint (canvas.js, line 402)
	CanvasGraphics_constructPath (canvas.js, line 1045)
	CanvasGraphics_executeOperatorList (canvas.js, line 773)
	InternalRenderTask__next (api.js, line 1630)
	InternalRenderTask__next ([native code], line 0)
[Log] PDF 316b108488f921409bc02990904f899b [1.6 iTextSharp™ 5.5.4 ©2000-2014 iText Group NV (AGPL-version) / -] (PDF.js: -) (viewer.js, line 1017)
[Log] Warning: Unsupported feature "unknown" (util.js, line 204)

Chrome: 
Warning: TT: more functions defined than expected
util.js:204 Warning: Could not find a preferred cmap table.
Unhandled promise rejection Promise {[[PromiseStatus]]: "rejected", [[PromiseValue]]: DOMException: Invalid font data in ArrayBuffer.}
util.js:219 Error: Bad encoding in flate stream, Warning: Unsupported feature "unknown"

**Comment by Rob--W** [comment]
Chromium 41.0.2272.77, PDF.js 1.0.1177, page 8:

```
viewer.js:6324 PDF 316b108488f921409bc02990904f899b [1.6 iTextSharp™ 5.5.4 ©2000-2014 iText Group NV (AGPL-version) / -] (PDF.js: 1.0.1177)
pdf.js:6317 Uncaught (in promise) 
DOMException: Invalid font data in ArrayBuffer. {message: "Invalid font data in ArrayBuffer.", name: "SyntaxError", code: 12, INDEX_SIZE_ERR: 1, DOMSTRING_SIZE_ERR: 2…}
pdf.worker.js:250 Error: Bad encoding in flate stream
pdf.worker.js:252     at error (chrome-extension://oemmndcbldboiebfnladdacbdfmadadm/content/build/pdf.worker.js:252:15)
    at Object.FlateStream_getCode [as getCode] (chrome-extension://oemmndcbldboiebfnladdacbdfmadadm/content/build/pdf.worker.js:31649:7)
    at Object.FlateStream_readBlock [as readBlock] (chrome-extension://oemmndcbldboiebfnladdacbdfmadadm/content/build/pdf.worker.js:31811:24)
    at Object.DecodeStream_getByte [as getByte] (chrome-extension://oemmndcbldboiebfnladdacbdfmadadm/content/build/pdf.worker.js:31367:14)
    at Object.Lexer_nextChar [as nextChar] (chrome-extension://oemmndcbldboiebfnladdacbdfmadadm/content/build/pdf.worker.js:30610:46)
    at Object.Lexer (chrome-extension://oemmndcbldboiebfnladdacbdfmadadm/content/build/pdf.worker.js:30552:10)
    at Object.EvaluatorPreprocessor (chrome-extension://oemmndcbldboiebfnladdacbdfmadadm/content/build/pdf.worker.js:12592:30)
    at Object.PartialEvaluator_getOperatorList [as getOperatorList] (chrome-extension://oemmndcbldboiebfnladdacbdfmadadm/content/build/pdf.worker.js:11103:26)
    at Object.PartialEvaluator_buildFormXObject [as buildFormXObject] (chrome-extension://oemmndcbldboiebfnladdacbdfmadadm/content/build/pdf.worker.js:10627:19)
pdf.worker.js:235 Warning: Unsupported feature "unknown"
```

On page 9, I get the "Bad encoding in flate stream" as well, but not the font error. Page 8 renders well, but page 9 does not.

**Comment by brendandahl** [comment]
I still see the bad flate stream error, but at least "cmap: Range glyph reference too high (2 > 1) (font-family: "g_d0_f53" style:normal weight:normal stretch:normal src index:0) source: (invalid URI)" is not fixed by #6715.

**Comment by tomaash** [comment]
I have the same problem with this pdf:
[wrong-pdf.pdf](https://github.com/mozilla/pdf.js/files/2053483/wrong-pdf.pdf)

**Comment by calixteman** [comment]
The link for the pdf in comment#0 is dead.
So it'd be nice if someone can attach here a faulty pdf, else we'll close this issue.

**Comment by Snuffleupagus** [comment]
WFM, using PDF.js: 5.7.85 [d6afffe8f] in Firefox 151.0a1 on Windows 11.
