### ISSUE TITLE
Rendering problem - Command token too long :128

### ISSUE THREAD

**Issue by santaclaus21** [mozilla/pdf.js#6108]
I've got an error while open http://dokumenty.jordan.pl/skany/2015_06/20150611_123718_42777.pdf.

`PDF.js v1.1.114 (kompilacja: 3fd44fd)
Wiadomość: Command token too long: 128
Stos: Error: Command token too long: 128
    at error (http://test.jordan.pl/faktury/js/pdf.js/build/pdf.worker.js:247:9)
    at Object.Lexer_getObj [as getObj] (http://test.jordan.pl/faktury/js/pdf.js/build/pdf.worker.js:31080:11)
    at Object.Parser_shift [as shift] (http://test.jordan.pl/faktury/js/pdf.js/build/pdf.worker.js:30169:32)
    at Object.Parser_makeStream [as makeStream] (http://test.jordan.pl/faktury/js/pdf.js/build/pdf.worker.js:30546:12)
    at Object.Parser_getObj [as getObj] (http://test.jordan.pl/faktury/js/pdf.js/build/pdf.worker.js:30214:28)
    at Object.XRef_fetchUncompressed [as fetchUncompressed] (http://test.jordan.pl/faktury/js/pdf.js/build/pdf.worker.js:4342:28)
    at Object.XRef_fetch [as fetch] (http://test.jordan.pl/faktury/js/pdf.js/build/pdf.worker.js:4299:26)
    at ObjectLoader_walk [as walk] (http://test.jordan.pl/faktury/js/pdf.js/build/pdf.worker.js:4726:37)
    at ObjectLoader_load [as load] (http://test.jordan.pl/faktury/js/pdf.js/build/pdf.worker.js:4706:12)
    at Object.resourceSuccess (http://test.jordan.pl/faktury/js/pdf.js/build/pdf.worker.js:2715:29)`

**Comment by timvandermeij** [comment]
I am able to reproduce this using the latest development version of PDF.js. For me this is a new one; thank you for reporting it!
