### ISSUE TITLE
Error: Unknown compression method in flate stream

### ISSUE THREAD

**Issue by xlc** [mozilla/pdf.js#6316]
I am getting this error for a password protected file and it is not happening for the original file without password. I added the password using OS X Preview.

File: https://drive.google.com/file/d/0B6YhVF9p-y2AVEJXSkdZazlOd2s/view?usp=sharing
The password is 'password'.
Original File (without password, doesn't have this error): https://drive.google.com/file/d/0B6YhVF9p-y2AOC1rZ1lmMmNELUk/view?usp=sharing

Using latest demo viewer. OS X 10.10.4
Happening on both Chrome 44.0.2403.125 and Firefox 39.0

```
Error: Unknown compression method in flate stream: 53, 212
2015-08-05 11:56:19.299 pdf.worker.js:233     at error (https://mozilla.github.io/pdf.js/build/pdf.worker.js:233:17)
    at Object.FlateStream (https://mozilla.github.io/pdf.js/build/pdf.worker.js:32028:7)
    at Object.Parser_makeFilter [as makeFilter] (https://mozilla.github.io/pdf.js/build/pdf.worker.js:30924:18)
    at Object.Parser_filter [as filter] (https://mozilla.github.io/pdf.js/build/pdf.worker.js:30885:21)
    at Object.Parser_makeStream [as makeStream] (https://mozilla.github.io/pdf.js/build/pdf.worker.js:30877:21)
    at Object.Parser_getObj [as getObj] (https://mozilla.github.io/pdf.js/build/pdf.worker.js:30491:28)
    at Object.XRef_fetchUncompressed [as fetchUncompressed] (https://mozilla.github.io/pdf.js/build/pdf.worker.js:4365:28)
    at Object.XRef_fetch [as fetch] (https://mozilla.github.io/pdf.js/build/pdf.worker.js:4322:26)
    at Object.metadata (https://mozilla.github.io/pdf.js/build/pdf.worker.js:3419:30)
2015-08-05 11:56:19.299 pdf.worker.js:224 Warning: Unsupported feature "unknown"
2015-08-05 11:56:19.300 pdf.worker.js:224 Warning: Invalid stream: "Error: Unknown compression method in flate stream: 53, 212"
2015-08-05 11:56:19.444 pdf.js:224 Warning: Unsupported feature "unknown"
2015-08-05 11:56:19.445 viewer.js:6722 PDF 308022624bb5d63ffc898d3c67edf5d7 [1.4 Mac OS X 10.10.3 Quartz PDFContext / Adobe InDesign CS5.5 (7.5.3)] (PDF.js: 1.1.366)
```

Although it looks like rendered fine.

**Comment by ufoqhmdt** [comment]
![image](https://user-images.githubusercontent.com/1751382/35266973-c71afab6-005f-11e8-9bd5-259b71757905.png)
same problem
