### ISSUE TITLE
Error: Required "glyf" or "loca" tables are not found

### ISSUE THREAD

**Issue by dman777** [mozilla/pdf.js#6533]
Using `PDFJS.version = '1.0.233';`, I am getting:

```
Error: Required "glyf" or "loca" tables are not found
pdf.worker.js:218     at error (http://104.239.146.237:9000/bower_components/pdfjs-bower/dist/pdf.worker.js:218:15)
    at Object.Font_checkAndRepair [as checkAndRepair] (http://104.239.146.237:9000/bower_components/pdfjs-bower/dist/pdf.worker.js:22407:11)
    at Object.Font (http://104.239.146.237:9000/bower_components/pdfjs-bower/dist/pdf.worker.js:20962:21)
    at Object.PartialEvaluator_translateFont [as translateFont] (http://104.239.146.237:9000/bower_components/pdfjs-bower/dist/pdf.worker.js:17108:14)
    at Object.PartialEvaluator_loadFont [as loadFont] (http://104.239.146.237:9000/bower_components/pdfjs-bower/dist/pdf.worker.js:16016:29)
    at Object.PartialEvaluator_handleSetFont [as handleSetFont] (http://104.239.146.237:9000/bower_components/pdfjs-bower/dist/pdf.worker.js:15789:19)
    at next (http://104.239.146.237:9000/bower_components/pdfjs-bower/dist/pdf.worker.js:16171:27)
    at http://104.239.146.237:9000/bower_components/pdfjs-bower/dist/pdf.worker.js:16176:19
pdf.worker.js:201 Warning: Unsupported feature "unknown"
pdf.worker.js:201 Warning: Unsupported feature "font"
pdf.js:201 Warning: Unsupported feature "unknown"
pdf.js:201 Warning: Unsupported feature "font"
pdf.js:201 Warning: Error during font loading: Required "glyf" or "loca" tables are not found
```

**Comment by Snuffleupagus** [comment]
When reporting an issue, please make sure that you read https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md.
As outlined in the *first* paragraph, at the very least you need to provide a link to the PDF file. (Or, you can also upload the file to GitHub, [as explained here](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/)).

**Comment by Rob--W** [comment]
@Snuffleupagus PDF files cannot be attached by non-repository members yet. Someone from Github support said to me that they're considering to allow it in the future. Non-members can share PDFs via their favorite file sharing site (Dropbox, Google Drive, OneDrive, ...) or mail it to us.

**Comment by dman777** [comment]
Here is the google drive link to the pdf file that is having the issue: https://drive.google.com/file/d/0B87JsTsyn1Z0Z0QzdXpnanoyYk0/view?usp=sharing

I placed in it also `This pdf was made with Adobe Acrobat PRO DC 2015 release 2015.009.20069`

**Comment by yurydelendik** [comment]
The embedded C2_20 font ('BAMPSQ+Raleway-Medium') contains empty glyf table (and loca table contains lots of zeros??),  so looks like our message about font being invalid is correct. PDF is showing as good as in other reader. Notice that other readers can silently ignore such error. 

Set verbosity level to error in a custom solution, to not see such warning. Closing as not an issue.
