### ISSUE TITLE
Display all the pages and divs, but no text

### ISSUE THREAD

**Issue by marcpires** [mozilla/pdf.js#7060]
When loading a file it show all the divs and file layout, but no information.
Below is the message that appears on Chrome console.

```
PDF 8f1576be1fdbf325a0159bbe2d697069 [1.4 GPL Ghostscript 8.15 / Adobe Acrobat 11.0.13] (PDF.js: 1.0.712)
pdf.worker.js:250 Error: Font MMType1 is not supported
pdf.worker.js:252     at error (http://192.168.0.104/organizer/organizer/modulos/contratos/_pdfjs/build/pdf.worker.js:252:15)
    at Object.Font (http://192.168.0.104/organizer/organizer/modulos/contratos/_pdfjs/build/pdf.worker.js:16409:9)
    at Object.PartialEvaluator_translateFont [as translateFont] (http://192.168.0.104/organizer/organizer/modulos/contratos/_pdfjs/build/pdf.worker.js:12045:14)
    at Object.PartialEvaluator_loadFont [as loadFont] (http://192.168.0.104/organizer/organizer/modulos/contratos/_pdfjs/build/pdf.worker.js:10853:16)
    at Object.PartialEvaluator_handleSetFont [as handleSetFont] (http://192.168.0.104/organizer/organizer/modulos/contratos/_pdfjs/build/pdf.worker.js:10625:19)
    at next (http://192.168.0.104/organizer/organizer/modulos/contratos/_pdfjs/build/pdf.worker.js:11014:27)
    at Object.PartialEvaluator_getOperatorList [as getOperatorList] (http://192.168.0.104/organizer/organizer/modulos/contratos/_pdfjs/build/pdf.worker.js:10951:14)
    at Object.<anonymous> (http://192.168.0.104/organizer/organizer/modulos/contratos/_pdfjs/build/pdf.worker.js:12090:28)
pdf.worker.js:235 Warning: Unsupported feature "unknown"
pdf.js:235 Warning: Unsupported feature "unknown"
pdf.worker.js:235 Warning: Unsupported feature "font"
pdf.js:235 Warning: Unsupported feature "font"
pdf.js:235 Warning: Error during font loading: Font MMType1 is not supported
pdf.worker.js:250 Error: Font MMType1 is not supported
pdf.worker.js:252     at error (http://192.168.0.104/organizer/organizer/modulos/contratos/_pdfjs/build/pdf.worker.js:252:15)
    at Object.Font (http://192.168.0.104/organizer/organizer/modulos/contratos/_pdfjs/build/pdf.worker.js:16409:9)
    at Object.PartialEvaluator_translateFont [as translateFont] (http://192.168.0.104/organizer/organizer/modulos/contratos/_pdfjs/build/pdf.worker.js:12045:14)
    at Object.PartialEvaluator_loadFont [as loadFont] (http://192.168.0.104/organizer/organizer/modulos/contratos/_pdfjs/build/pdf.worker.js:10853:16)
    at Object.PartialEvaluator_handleSetFont [as handleSetFont] (http://192.168.0.104/organizer/organizer/modulos/contratos/_pdfjs/build/pdf.worker.js:10625:19)
    at next (http://192.168.0.104/organizer/organizer/modulos/contratos/_pdfjs/build/pdf.worker.js:11014:27)
    at Object.PartialEvaluator_getOperatorList [as getOperatorList] (http://192.168.0.104/organizer/organizer/modulos/contratos/_pdfjs/build/pdf.worker.js:10951:14)
    at Object.<anonymous> (http://192.168.0.104/organizer/organizer/modulos/contratos/_pdfjs/build/pdf.worker.js:12090:28)
pdf.worker.js:235 Warning: Unsupported feature "unknown"
pdf.js:235 Warning: Unsupported feature "unknown"
pdf.worker.js:235 Warning: Unsupported feature "font"
pdf.js:235 Warning: Unsupported feature "font"
pdf.js:235 Warning: Error during font loading: Font MMType1 is not supported
pdf.worker.js:250 Error: Font MMType1 is not supported
pdf.worker.js:252     at error (http://192.168.0.104/organizer/organizer/modulos/contratos/_pdfjs/build/pdf.worker.js:252:15)
    at Object.Font (http://192.168.0.104/organizer/organizer/modulos/contratos/_pdfjs/build/pdf.worker.js:16409:9)
    at Object.PartialEvaluator_translateFont [as translateFont] (http://192.168.0.104/organizer/organizer/modulos/contratos/_pdfjs/build/pdf.worker.js:12045:14)
    at Object.PartialEvaluator_loadFont [as loadFont] (http://192.168.0.104/organizer/organizer/modulos/contratos/_pdfjs/build/pdf.worker.js:10853:16)
    at Object.PartialEvaluator_handleSetFont [as handleSetFont] (http://192.168.0.104/organizer/organizer/modulos/contratos/_pdfjs/build/pdf.worker.js:10625:19)
    at next (http://192.168.0.104/organizer/organizer/modulos/contratos/_pdfjs/build/pdf.worker.js:11014:27)
    at Object.PartialEvaluator_getOperatorList [as getOperatorList] (http://192.168.0.104/organizer/organizer/modulos/contratos/_pdfjs/build/pdf.worker.js:10951:14)
    at Object.<anonymous> (http://192.168.0.104/organizer/organizer/modulos/contratos/_pdfjs/build/pdf.worker.js:12090:28)
pdf.worker.js:235 Warning: Unsupported feature "unknown"
pdf.js:235 Warning: Unsupported feature "unknown"
pdf.worker.js:235 Warning: Unsupported feature "font"
pdf.js:235 Warning: Unsupported feature "font"
pdf.js:235 Warning: Error during font loading: Font MMType1 is not supported
pdf.worker.js:250 Error: Font MMType1 is not supported
pdf.worker.js:252     at error (http://192.168.0.104/organizer/organizer/modulos/contratos/_pdfjs/build/pdf.worker.js:252:15)
    at Object.Font (http://192.168.0.104/organizer/organizer/modulos/contratos/_pdfjs/build/pdf.worker.js:16409:9)
    at Object.PartialEvaluator_translateFont [as translateFont] (http://192.168.0.104/organizer/organizer/modulos/contratos/_pdfjs/build/pdf.worker.js:12045:14)
    at Object.PartialEvaluator_loadFont [as loadFont] (http://192.168.0.104/organizer/organizer/modulos/contratos/_pdfjs/build/pdf.worker.js:10853:16)
    at Object.PartialEvaluator_handleSetFont [as handleSetFont] (http://192.168.0.104/organizer/organizer/modulos/contratos/_pdfjs/build/pdf.worker.js:10625:19)
    at next (http://192.168.0.104/organizer/organizer/modulos/contratos/_pdfjs/build/pdf.worker.js:11014:27)
    at Object.PartialEvaluator_getOperatorList [as getOperatorList] (http://192.168.0.104/organizer/organizer/modulos/contratos/_pdfjs/build/pdf.worker.js:10951:14)
    at Object.<anonymous> (http://192.168.0.104/organizer/organizer/modulos/contratos/_pdfjs/build/pdf.worker.js:12090:28)
pdf.worker.js:235 Warning: Unsupported feature "unknown"
pdf.js:235 Warning: Unsupported feature "unknown"
pdf.worker.js:235 Warning: Unsupported feature "font"
pdf.js:235 
Warning: Unsupported feature "font"
pdf.js:235 
Warning: Error during font loading: Font MMType1 is not supported
```

**Comment by marcpires** [comment]
Replaced pdf.js and pdf.worker.js for the current version and it worked.
