### ISSUE TITLE
Worker file cannot be minified using UglifyJS

### ISSUE THREAD

**Issue by redhead** [mozilla/pdf.js#7326]
We are using webpack for bundling and for production we minimize our bundles and chunks using UglifyJS (plugin for webpack). 

When it tries to uglify pdf.js (pdfjs-dist) worker file it crashes with the following message

    WARN: Side effects in initialization of unused variable scanLength [null:1374,16]
    WARN: Side effects in initialization of unused variable PageViewport [null:3253,4]
    undefined:0
    (function(MOZ_SourceMap,exports
    ^
    RangeError: Maximum call stack size exceeded
        at Object.before (eval at <anonymous> (C:\HB\ugly\node_modules\uglify-js\tools\node.js:24:4), <anonymous>)
        at AST_Node.eval [as transform] (eval at <anonymous> (C:\HB\ugly\node_modules\uglify-js\tools\node.js:24:4), <anonymous>:2902:35)
        at eval (eval at <anonymous> (C:\HB\ugly\node_modules\uglify-js\tools\node.js:24:4), <anonymous>:3024:43)
        at AST_Node.eval [as transform] (eval at <anonymous> (C:\HB\ugly\node_modules\uglify-js\tools\node.js:24:4), <anonymous>:2906:21)
        at eval (eval at <anonymous> (C:\HB\ugly\node_modules\uglify-js\tools\node.js:24:4), <anonymous>:3037:31)
        at AST_Node.eval [as transform] (eval at <anonymous> (C:\HB\ugly\node_modules\uglify-js\tools\node.js:24:4), <anonymous>:2906:21)
        at eval (eval at <anonymous> (C:\HB\ugly\node_modules\uglify-js\tools\node.js:24:4), <anonymous>:3019:29)
        at AST_Node.eval [as transform] (eval at <anonymous> (C:\HB\ugly\node_modules\uglify-js\tools\node.js:24:4), <anonymous>:2906:21)
        at eval (eval at <anonymous> (C:\HB\ugly\node_modules\uglify-js\tools\node.js:24:4), <anonymous>:3020:29)
        at AST_Node.eval [as transform] (eval at <anonymous> (C:\HB\ugly\node_modules\uglify-js\tools\node.js:24:4), <anonymous>:2906:21)

This started happening with pdf-js build 1.4.31 (before that it worked minified nicely) all the way to now-stable 1.4.265 and also 1.5.* beta versions.

**Comment by Snuffleupagus** [comment]
Are you using the `gulp minified` command to minify the files?
If not, I'm guessing that you may be missing the following workaround: https://github.com/mozilla/pdf.js/blob/1c0433586e1d2e59c2d93f4b565a28055eaaeeb4/make.js#L592-L593, see also issue #7044.

**Comment by redhead** [comment]
We are using pdfjs-dist, so we are not building pdf.js ourselves. I tried the uglify js option sequences set to false that you referenced, and seems to work. Thanks.

**Comment by yurydelendik** [comment]
Also it shall be fixed in Uglify (see https://github.com/mishoo/UglifyJS2/issues/1038) and filed bug for Chrome (https://bugs.chromium.org/p/chromium/issues/detail?id=602262). Closing  as answered.

**Comment by redhead** [comment]
Ok. Thanks for your help.
