### ISSUE TITLE
Unable to create mozcentraldiff

### ISSUE THREAD

**Issue by rvandermeulen** [mozilla/pdf.js#7743]
I'm trying to update the in-tree copy of pdf.js in mozilla-central from version 1.2.234 to rev 7e392c0 via |BASELINE=bc3bceb node make mozcentralbaseline mozcentraldiff|. I'm getting the following error, even after clobbering my /build directory:

### Building mozilla-central extension
module.js:328
    throw err;
    ^

Error: Cannot find module 'run-sequence'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ryanvm/repos/pdfjs/gulpfile.js:25:19)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)

**Comment by rvandermeulen** [comment]
Nevermind, I updated my npm environment and all is well.
