### ISSUE TITLE
Issue with IE 10 browser on Latest PDFjs Library

### ISSUE THREAD

**Issue by venusakthiv** [mozilla/pdf.js#7984]
Link to PDF file (or attach file here): Any PDF's

Configuration:
- Web browser and its version: IE 10 
- Operating system and its version: Windows 7 & 8
- PDF.js version: Latest
- Is an extension:

Steps to reproduce the problem:
1.  open IE 10 on Win 7/8
2. enter the url http://mozilla.github.io/pdf.js/web/viewer.html and check you get an error "DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
viewer.html
HTML1300: Navigation occurred.
viewer.html
Warning: Unhandled rejection: TypeError: Unable to get property 'firstElementChild' of undefined or null reference
TypeError: Unable to get property 'firstElementChild' of undefined or null reference
   at PDFViewer (http://mozilla.github.io/pdf.js/web/viewer.js:4959:6)
   at Anonymous function (http://mozilla.github.io/pdf.js/web/viewer.js:5791:7)
   at Promise (http://mozilla.github.io/pdf.js/build/pdf.js:1291:7)
   at PDFViewerApplication._initializeViewerComponents (http://mozilla.github.io/pdf.js/web/viewer.js:5779:6)
   at Anonymous function (http://mozilla.github.io/pdf.js/web/viewer.js:5693:7)
   at runHandlers (http://mozilla.github.io/pdf.js/build/pdf.js:1221:11)
"

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by venusakthiv** [comment]
Thanks All. it works!!!

**Comment by lihepeng062** [comment]
what is [4-ie10-specific]? I want to get downlond URL.
