### ISSUE TITLE
Error: JPEG error: unknown marker 2e00 

### ISSUE THREAD

**Issue by balmydrizzle** [mozilla/pdf.js#8169]
Link to problematic PDF: [prob1.pdf](http://210.243.166.143/prob1.pdf)
Link to pdf.js we use (I zip mozillaPDF folder into a zip): [mpdf.zip](http://210.243.166.143/mpdf.zip)

Configuration:
- Web browser and its version: _Chrome v44_
- Operating system and its version: _Win7 Pro 64bit_
- PDF.js version: _1.6.230_
- Is an extension: _not sure_

Steps to reproduce the problem:
1. Just open it using pdf.js and see error messsage in console.
2.All other pdf reader s/w or browser plugin CAN sohw image well.

What is the expected behavior? (add screenshot) Should show a single image in pdf.js

What went wrong? (add screenshot) show blank in pdf.js aftrer pdf downloaded. browser console shows:"
PDF e125b57ca39f9091e0558b41122f6a89 [1.3 Image2PDF (http://www.verypdf.com) / Image2PDF Command Line Software] (PDF.js: 1.6.230) viewer.js:8269
Error: JPEG error: unknown marker 2e00 pdf.js:10392
at error (http://un.udndata.com/mozillaPDF/build/pdf.worker.js:1299:17)
at Object.parse (http://un.udndata.com/mozillaPDF/build/pdf.worker.js:11971:13)
at Object.JpegStream_ensureBuffer [as ensureBuffer] (http://un.udndata.com/mozillaPDF/build/pdf.worker.js:20747:15)
at Object.JpegStream_getBytes [as getBytes] (http://un.udndata.com/mozillaPDF/build/pdf.worker.js:20756:10)
at Object.PDFImage_getImageBytes [as getImageBytes] (http://un.udndata.com/mozillaPDF/build/pdf.worker.js:34560:25)
at Object.PDFImage_createImageData [as createImageData] (http://un.udndata.com/mozillaPDF/build/pdf.worker.js:34435:27)
at Object.onResolve (http://un.udndata.com/mozillaPDF/build/pdf.worker.js:37363:34)
at Object.runHandlers (http://un.udndata.com/mozillaPDF/build/pdf.worker.js:2250:35) pdf.js:10392
Warning: Unable to decode image: Error: JPEG error: unknown marker 2e00 pdf.js:10392
Warning: Dependent image isn't ready yet
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
We embed pdf.js in our web page but that's paid-service pages, so I put pdf.js and the pdf.js (zip mozillaPDF folder as a zip file) on web server as public links for you tech guys to analazye.

**Comment by balmydrizzle** [comment]
Sorry, I put wrong console error message. That's error of another wrong pdf file. Following are error emssage in console corresponding to prob1.pdf:

PDF e125b57ca39f9091e0558b41122f6a89 [1.3 Image2PDF (http://www.verypdf.com) / Image2PDF Command Line Software] (PDF.js: 1.6.230) viewer.js:8269
Error: JPEG error: unknown marker 2e00 pdf.js:10392
    at error (http://un.udndata.com/mozillaPDF/build/pdf.worker.js:1299:17)
    at Object.parse (http://un.udndata.com/mozillaPDF/build/pdf.worker.js:11971:13)
    at Object.JpegStream_ensureBuffer [as ensureBuffer] (http://un.udndata.com/mozillaPDF/build/pdf.worker.js:20747:15)
    at Object.JpegStream_getBytes [as getBytes] (http://un.udndata.com/mozillaPDF/build/pdf.worker.js:20756:10)
    at Object.PDFImage_getImageBytes [as getImageBytes] (http://un.udndata.com/mozillaPDF/build/pdf.worker.js:34560:25)
    at Object.PDFImage_createImageData [as createImageData] (http://un.udndata.com/mozillaPDF/build/pdf.worker.js:34435:27)
    at Object.onResolve (http://un.udndata.com/mozillaPDF/build/pdf.worker.js:37363:34)
    at Object.runHandlers (http://un.udndata.com/mozillaPDF/build/pdf.worker.js:2250:35) pdf.js:10392
Warning: Unable to decode image: Error: JPEG error: unknown marker 2e00 pdf.js:10392
Warning: Dependent image isn't ready yet
