### ISSUE TITLE
GitHub pages not updated

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#8290]
It looks like #8288 broke something as `gh-pages` and `pdfjs-dist` have not been updated after merging.

/cc @yurydelendik

**Comment by brendandahl** [comment]
Error: EPERM: operation not permitted, unlink 'C:\pdfjs\botio-files-pdfjs\privat                          e\5491f4a4ea42b1d\build\dist\.git\objects\pack\pack-ffcf8ee2531e435088a075400de6                          5de97c56cbf8.idx'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:1089:18)
    at _unlinkSync (C:\Users\Administrator\AppData\Roaming\npm\node_modules\boti                          o\node_modules\shelljs\shell.js:1398:10)
    at rmdirSyncRecursive (C:\Users\Administrator\AppData\Roaming\npm\node_modul                          es\botio\node_modules\shelljs\shell.js:1145:9)
    at rmdirSyncRecursive (C:\Users\Administrator\AppData\Roaming\npm\node_modul                          es\botio\node_modules\shelljs\shell.js:1135:7)
    at rmdirSyncRecursive (C:\Users\Administrator\AppData\Roaming\npm\node_modul                          es\botio\node_modules\shelljs\shell.js:1135:7)
    at rmdirSyncRecursive (C:\Users\Administrator\AppData\Roaming\npm\node_modul                          es\botio\node_modules\shelljs\shell.js:1135:7)
    at rmdirSyncRecursive (C:\Users\Administrator\AppData\Roaming\npm\node_modul                          es\botio\node_modules\shelljs\shell.js:1135:7)
    at rmdirSyncRecursive (C:\Users\Administrator\AppData\Roaming\npm\node_modul                          es\botio\node_modules\shelljs\shell.js:1135:7)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\botio\node_module                          s\shelljs\shell.js:384:7

**Comment by timvandermeij** [comment]
Interestingly, the `gh-pages` branch has been updated after the most recent merge. Only `pdfjs-dist` is not updated now.

**Comment by timvandermeij** [comment]
Both problems are now resolved, so I'm closing this as fixed.
