### ISSUE TITLE
Error when trying to build source

### ISSUE THREAD

**Issue by LubenZA** [mozilla/pdf.js#8444]
Hi,

I am getting the following error when trying to 'gulp generic'

module.js:471
    throw err;
    ^

Error: Cannot find module 'gulp-rename'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Applications/XAMPP/xamppfiles/htdocs/CorePDFJS/pdf.js/gulpfile.js:24:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

Downloaded the latest source today.
node.js v6.10.3

Best Regards,

**Comment by Snuffleupagus** [comment]
Did you follow *all* of the steps in https://github.com/mozilla/pdf.js#getting-the-code, since the `npm install` command should install all required dependencies?

**Comment by LubenZA** [comment]
Ah thank you!
