### ISSUE TITLE
Refused to get unsafe header "Accept-Ranges"

### ISSUE THREAD

**Issue by chnljx** [mozilla/pdf.js#8648]
Error: Invalid XRef stream header
nbfile.guyitai.net/pdfjs/build/pdf.worker.js:340     at error (http://nbfile.guyitai.net/pdfjs/build/pdf.worker.js:340:17)
    at XRef_readXRef [as readXRef] (http://nbfile.guyitai.net/pdfjs/build/pdf.worker.js:20943:13)
    at XRef_parse [as parse] (http://nbfile.guyitai.net/pdfjs/build/pdf.worker.js:20613:28)
    at PDFDocument_setup [as setup] (http://nbfile.guyitai.net/pdfjs/build/pdf.worker.js:26445:17)
    at PDFDocument_parse [as parse] (http://nbfile.guyitai.net/pdfjs/build/pdf.worker.js:26336:12)
    at http://nbfile.guyitai.net/pdfjs/build/pdf.worker.js:36120:28
    at Promise (<anonymous>)
    at LocalPdfManager_ensure [as ensure] (http://nbfile.guyitai.net/pdfjs/build/pdf.worker.js:36115:14)
    at LocalPdfManager.BasePdfManager_ensureDoc [as ensureDoc] (http://nbfile.guyitai.net/pdfjs/build/pdf.worker.js:36067:19)
nbfile.guyitai.net/pdfjs/build/pdf.worker.js:331 Warning: Indexing all PDF objects

most of pdf no problem, but any pdf have this error.

**Comment by Gabri-connect** [comment]
Not fixed. I just downloaded the latest version, and getting same issue. The file is hosted on amazon AWS S3 platform. I have applied the custom CORS config already. Still not working
