### ISSUE TITLE
"The API version "undefined" does not match the Worker version "2.0.290"

### ISSUE THREAD

**Issue by mtembi** [mozilla/pdf.js#9406]
I am testing using fpdf to generate pdf stream in wordpress. The stream is returned to jquery as a base64encoded stream:

`function generatePdf(){
        
        include_once(plugin_dir_path( __DIR__ ).'common/pdf/fpdf.php');
        $pdf = new FPDF();
        $pdf->AddPage();
        $pdf->SetFont('Arial','B',16);
        $pdf->Cell(40,10,'Hello World!');
        $pdf->Close();
        $pdf_contents=$pdf->Output("S", '');
        $pdfBase64=base64_encode($pdf_contents);
        echo $pdfBase64;        
        die();
    }`

The jquery code to pull the data is basedd on [https://jsfiddle.net/pdfjs/cq0asLqz/?utm_source=website&utm_medium=embed&utm_campaign=cq0asLqz](jsfiddle)

My code is as follows:

`jQuery.ajax({
					url:bk_pdf_object.ajax_url,
					dataType:"text",
					data:{
						"action":"bk_pdf_handler"
					},
					method:"POST",
					beforeSend:function(){
						console.log("sending for pdf");
					},
					success:function(data){
						console.log("got data from php");
						console.log(data);
						//convert to b
						var pdfData=atob(data);						
						try{
							PDFJS.workerSrc="https://mozilla.github.io/pdf.js/build/pdf.worker.js";
							
							var loadingTask=PDFJS.getDocument({data:pdfData});
							loadingTask.promise.then(function(pdf){
								var pageNumber=1;
								pdf.getPage(pageNumber).then(function(page){
									console.log('Page loaded');
									var scale=1.5;
									var viewport=page.getViewport(scale);
									var canvas=jQuery("canvas#bkPdfCanvas")[0];
									console.log(canvas);
									var context=canvas.getContext("2d");
									canvas.height=viewport.height;
									canvas.width=viewport.width;
									
									var renderContext={
											canvasContext:canvas,
											viewport:viewport
									};
									var renderTask=page.render(renderContext);
									renderTask.then(function(){
										console.log('page rendered');
									});
								});
							}, function(reason){
								console.error(reason);
							});
						}catch(err){
							console.error(err);
						}
					},
					error:function(xhr, status, errorThrown){
						console.error(errorThrown);
					},
					complete:function(){
						console.log('Pdf generation complete');
					}
				});`
I am getting a version error as follows:
`UnknownErrorException {name: "UnknownErrorException", message: "The API version "undefined" does not match the Worker version "2.0.290".", details: "Error: The API version "undefined" does not match the Worker version "2.0.290"."}`

with some extra info
`Error at UnknownErrorExceptionClosure (http://172.17.0.5/wp-content/plugins/Idl_Pdf/common/pdfjs/pdf.js:447:37) at Object.defineProperty.value (http://172.17.0.5/wp-content/plugins/Idl_Pdf/common/pdfjs/pdf.js:450:2) at __w_pdfjs_require__ (http://172.17.0.5/wp-content/plugins/Idl_Pdf/common/pdfjs/pdf.js:45:30) at Object._typeof (http://172.17.0.5/wp-content/plugins/Idl_Pdf/common/pdfjs/pdf.js:12336:23) at __w_pdfjs_require__ (http://172.17.0.5/wp-content/plugins/Idl_Pdf/common/pdfjs/pdf.js:45:30) at Object.defineProperty.value (http://172.17.0.5/wp-content/plugins/Idl_Pdf/common/pdfjs/pdf.js:91:18) at http://172.17.0.5/wp-content/plugins/Idl_Pdf/common/pdfjs/pdf.js:94:10 at webpackUniversalModuleDefinition (http://172.17.0.5/wp-content/plugins/Idl_Pdf/common/pdfjs/pdf.js:24:59) at http://172.17.0.5/wp-content/plugins/Idl_Pdf/common/pdfjs/pdf.js:25:3`

I am a newbie at wordpress plugin development and am trying out pdf.js to see how well the two can work together. 
Thanks

Configuration:
- Google Chrome Version 63.0.3239.132 (Official Build) (64-bit):
- OS: Fedora 27:
- PDF.js 1.9.426:
- No:

Steps to reproduce the problem:
1.  
2.

What is the expected behavior? (add screenshot)
A pdf in a canvas

What went wrong? (add screenshot)
Got an error on unmatched version of pdf.worker.js

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by mtembi** [comment]
It's a false alarm I guess. I've looked at the error again and noticed the pdf.js and pdf.worker,js libraries are local
`http://172.17.0.5/wp-content/plugins/Idl_Pdf/common/pdfjs/pdf.js:25:3`
but I have set the PDFJS.workerSrc to the online one
`PDFJS.workerSrc="https://mozilla.github.io/pdf.js/build/pdf.worker.js";`

I have corrected and on my way again. sorry
