### ISSUE TITLE
Warning: Unable to decode image: UnknownErrorException: "document" is not defined.

### ISSUE THREAD

**Issue by Ayrtonalec** [mozilla/pdf.js#9533]
I've recently been getting this error `Warning: Unable to decode image: UnknownErrorException: "document" is not defined. ` with some pdf files.

Working PDF:
[angled_3.pdf](https://github.com/mozilla/pdf.js/files/1784253/angled_3.pdf)

PDF resulting into the error : [flyer wijk.pdf](https://github.com/mozilla/pdf.js/files/1784245/flyer.wijk.pdf)

I'm trying to gather the base64 from the images within the pdf by calling `JpegStream in pdf.js on line 4610`, it still recognizes the images and giving them custom names like img_p1_1 and img_p2_1 but it gives it no objs or base64.

The wanted result is it getting the base64 of the images within the pdf and resolving the error (The error only occurs with the pdf that does not supply me the base64 of the images)

Configuration:
- NodeJS

If anyone requires more information I'd be happy to supply!

UPDATE: Adding two lines.

**Comment by Rob--W** [comment]
Can you provide a full example that results in this error? I guess that you're using an example based on examples/node/pdf2png/pdf2png.js, but I'm not sure.

Also, which Node.js version are you using?

I think that the issue may be caused by #9427

**Comment by Ayrtonalec** [comment]
I've updated nodeJS to the newest version v9.8.0, I've build my own application using The operator list and gathering the base64 of the images using pdf.js from the build folder inside the switch case `JpegStream`.

I've managed to gather additional error information: 
`Warning: Native JPEG decoding failed -- trying to recover: Image is not defined
(node:21844) UnhandledPromiseRejectionWarning: ReferenceError: document is not defined
    at FontLoader.fontLoaderInsertRule [as insertRule] (/home/ec2-user/environment/pdf-parser/node_modules/pdfjs-dist/build/pdf.js:10777:48)
    at FontLoader.fontLoaderBind [as bind] (/home/ec2-user/environment/pdf-parser/node_modules/pdfjs-dist/build/pdf.js:10835:22)
    at WorkerTransport.transportObj (/home/ec2-user/environment/pdf-parser/node_modules/pdfjs-dist/build/pdf.js:10292:35)
    at LoopbackPort.MessageHandler._onComObjOnMessage (/home/ec2-user/environment/pdf-parser/node_modules/pdfjs-dist/build/pdf.js:1158:25)
    at LoopbackPort.<anonymous> (/home/ec2-user/environment/pdf-parser/node_modules/pdfjs-dist/build/pdf.js:9803:26)
    at Array.forEach (<anonymous>)
    at /home/ec2-user/environment/pdf-parser/node_modules/pdfjs-dist/build/pdf.js:9802:33
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
    at emitWarning (internal/process/promises.js:48:15)
    at emitPromiseRejectionWarnings (internal/process/promises.js:103:9)
    at process._tickCallback (internal/process/next_tick.js:119:42)
(node:21844) ReferenceError: document is not defined
    at FontLoader.fontLoaderInsertRule [as insertRule] (/home/ec2-user/environment/pdf-parser/node_modules/pdfjs-dist/build/pdf.js:10777:48)
    at FontLoader.fontLoaderBind [as bind] (/home/ec2-user/environment/pdf-parser/node_modules/pdfjs-dist/build/pdf.js:10835:22)
    at WorkerTransport.transportObj (/home/ec2-user/environment/pdf-parser/node_modules/pdfjs-dist/build/pdf.js:10292:35)
    at LoopbackPort.MessageHandler._onComObjOnMessage (/home/ec2-user/environment/pdf-parser/node_modules/pdfjs-dist/build/pdf.js:1158:25)
    at LoopbackPort.<anonymous> (/home/ec2-user/environment/pdf-parser/node_modules/pdfjs-dist/build/pdf.js:9803:26)
    at Array.forEach (<anonymous>)
    at /home/ec2-user/environment/pdf-parser/node_modules/pdfjs-dist/build/pdf.js:9802:33
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
(node:21844) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:78:13)
    at emitWarning (internal/process/promises.js:71:3)
    at emitPromiseRejectionWarnings (internal/process/promises.js:103:9)
    at process._tickCallback (internal/process/next_tick.js:119:42)
(node:21844) UnhandledPromiseRejectionWarning: ReferenceError: document is not defined
    at FontLoader.fontLoaderInsertRule [as insertRule] (/home/ec2-user/environment/pdf-parser/node_modules/pdfjs-dist/build/pdf.js:10777:48)
    at FontLoader.fontLoaderBind [as bind] (/home/ec2-user/environment/pdf-parser/node_modules/pdfjs-dist/build/pdf.js:10835:22)
    at WorkerTransport.transportObj (/home/ec2-user/environment/pdf-parser/node_modules/pdfjs-dist/build/pdf.js:10292:35)
    at LoopbackPort.MessageHandler._onComObjOnMessage (/home/ec2-user/environment/pdf-parser/node_modules/pdfjs-dist/build/pdf.js:1158:25)
    at LoopbackPort.<anonymous> (/home/ec2-user/environment/pdf-parser/node_modules/pdfjs-dist/build/pdf.js:9803:26)
    at Array.forEach (<anonymous>)
    at /home/ec2-user/environment/pdf-parser/node_modules/pdfjs-dist/build/pdf.js:9802:33
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
    at emitWarning (internal/process/promises.js:48:15)
    at emitPromiseRejectionWarnings (internal/process/promises.js:103:9)
    at process._tickCallback (internal/process/next_tick.js:119:42)
(node:21844) ReferenceError: document is not defined
    at FontLoader.fontLoaderInsertRule [as insertRule] (/home/ec2-user/environment/pdf-parser/node_modules/pdfjs-dist/build/pdf.js:10777:48)
    at FontLoader.fontLoaderBind [as bind] (/home/ec2-user/environment/pdf-parser/node_modules/pdfjs-dist/build/pdf.js:10835:22)
    at WorkerTransport.transportObj (/home/ec2-user/environment/pdf-parser/node_modules/pdfjs-dist/build/pdf.js:10292:35)
    at LoopbackPort.MessageHandler._onComObjOnMessage (/home/ec2-user/environment/pdf-parser/node_modules/pdfjs-dist/build/pdf.js:1158:25)
    at LoopbackPort.<anonymous> (/home/ec2-user/environment/pdf-parser/node_modules/pdfjs-dist/build/pdf.js:9803:26)
    at Array.forEach (<anonymous>)
    at /home/ec2-user/environment/pdf-parser/node_modules/pdfjs-dist/build/pdf.js:9802:33
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
(node:21844) UnhandledPromiseRejectionWarning: ReferenceError: document is not defined
    at FontLoader.fontLoaderInsertRule [as insertRule] (/home/ec2-user/environment/pdf-parser/node_modules/pdfjs-dist/build/pdf.js:10777:48)
    at FontLoader.fontLoaderBind [as bind] (/home/ec2-user/environment/pdf-parser/node_modules/pdfjs-dist/build/pdf.js:10835:22)
    at WorkerTransport.transportObj (/home/ec2-user/environment/pdf-parser/node_modules/pdfjs-dist/build/pdf.js:10292:35)
    at LoopbackPort.MessageHandler._onComObjOnMessage (/home/ec2-user/environment/pdf-parser/node_modules/pdfjs-dist/build/pdf.js:1158:25)
    at LoopbackPort.<anonymous> (/home/ec2-user/environment/pdf-parser/node_modules/pdfjs-dist/build/pdf.js:9803:26)
    at Array.forEach (<anonymous>)
    at /home/ec2-user/environment/pdf-parser/node_modules/pdfjs-dist/build/pdf.js:9802:33
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
    at emitWarning (internal/process/promises.js:48:15)
    at emitPromiseRejectionWarnings (internal/process/promises.js:103:9)
    at process._tickCallback (internal/process/next_tick.js:119:42)
(node:21844) ReferenceError: document is not defined
    at FontLoader.fontLoaderInsertRule [as insertRule] (/home/ec2-user/environment/pdf-parser/node_modules/pdfjs-dist/build/pdf.js:10777:48)
    at FontLoader.fontLoaderBind [as bind] (/home/ec2-user/environment/pdf-parser/node_modules/pdfjs-dist/build/pdf.js:10835:22)
    at WorkerTransport.transportObj (/home/ec2-user/environment/pdf-parser/node_modules/pdfjs-dist/build/pdf.js:10292:35)
    at LoopbackPort.MessageHandler._onComObjOnMessage (/home/ec2-user/environment/pdf-parser/node_modules/pdfjs-dist/build/pdf.js:1158:25)
    at LoopbackPort.<anonymous> (/home/ec2-user/environment/pdf-parser/node_modules/pdfjs-dist/build/pdf.js:9803:26)
    at Array.forEach (<anonymous>)
    at /home/ec2-user/environment/pdf-parser/node_modules/pdfjs-dist/build/pdf.js:9802:33
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
(node:21844) UnhandledPromiseRejectionWarning: ReferenceError: document is not defined
    at FontLoader.fontLoaderInsertRule [as insertRule] (/home/ec2-user/environment/pdf-parser/node_modules/pdfjs-dist/build/pdf.js:10777:48)
    at FontLoader.fontLoaderBind [as bind] (/home/ec2-user/environment/pdf-parser/node_modules/pdfjs-dist/build/pdf.js:10835:22)
    at WorkerTransport.transportObj (/home/ec2-user/environment/pdf-parser/node_modules/pdfjs-dist/build/pdf.js:10292:35)
    at LoopbackPort.MessageHandler._onComObjOnMessage (/home/ec2-user/environment/pdf-parser/node_modules/pdfjs-dist/build/pdf.js:1158:25)
    at LoopbackPort.<anonymous> (/home/ec2-user/environment/pdf-parser/node_modules/pdfjs-dist/build/pdf.js:9803:26)
    at Array.forEach (<anonymous>)
    at /home/ec2-user/environment/pdf-parser/node_modules/pdfjs-dist/build/pdf.js:9802:33
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
    at emitWarning (internal/process/promises.js:48:15)
    at emitPromiseRejectionWarnings (internal/process/promises.js:103:9)
    at process._tickCallback (internal/process/next_tick.js:119:42)
(node:21844) ReferenceError: document is not defined
    at FontLoader.fontLoaderInsertRule [as insertRule] (/home/ec2-user/environment/pdf-parser/node_modules/pdfjs-dist/build/pdf.js:10777:48)
    at FontLoader.fontLoaderBind [as bind] (/home/ec2-user/environment/pdf-parser/node_modules/pdfjs-dist/build/pdf.js:10835:22)
    at WorkerTransport.transportObj (/home/ec2-user/environment/pdf-parser/node_modules/pdfjs-dist/build/pdf.js:10292:35)
    at LoopbackPort.MessageHandler._onComObjOnMessage (/home/ec2-user/environment/pdf-parser/node_modules/pdfjs-dist/build/pdf.js:1158:25)
    at LoopbackPort.<anonymous> (/home/ec2-user/environment/pdf-parser/node_modules/pdfjs-dist/build/pdf.js:9803:26)
    at Array.forEach (<anonymous>)
    at /home/ec2-user/environment/pdf-parser/node_modules/pdfjs-dist/build/pdf.js:9802:33
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)`

And've been trying to work from there on forward but no succes yet. I'm honestly lost on what generates this error and prevents me from reading the base64 of images.

**Comment by Ayrtonalec** [comment]
Extra info: The first working file `angled_3` crashed with the above given error, I figured it might be a better idea to start here instead of the bigger pdf `flyer wijk` there are two images in that file.

**Comment by Rob--W** [comment]
> I've build my own application

For reproduction, please also include the source code of a minimal Node.js application that generates the above error.

**Comment by Ayrtonalec** [comment]
https://github.com/Ayrtonalec/Work

I'm sorry for the repository mess, I'm cleaning it up.
 
Run the app.1.js and add as url Get parameter `?filter=image`

**Comment by Ayrtonalec** [comment]
Anyone who'd have any idea? :/

**Comment by Rob--W** [comment]
That's too much code to dig through. Can you reduce it to a minimal example?

Have you tried using the `nativeImageDecoderSupport` option in `pdfjsLib.getDocument`?
https://github.com/mozilla/pdf.js/blob/6662985a20b769d7e78e7cf4486eb6b7130f0cf0/src/display/api.js#L138-L145

It would be something like this:
```javascript
pdfjsLib.getDocument({
  url: pdfPath,
  nativeImageDecoderSupport: pdfjsLib.NativeImageDecoding.NONE,
}).then(function(document) {
  // ...
});
```

**Comment by Ayrtonalec** [comment]
If I disable NativeImageDecoing like the example I wont get the error, but the images wont read either.
I'll try to reduce my code to a minimal example.

Thanks for helping, I know it isn't easy and isn't a lot to go on. I really appreciate your help.

**Comment by Snuffleupagus** [comment]
Both of the PDF documents from https://github.com/mozilla/pdf.js/issues/9533#issue-302622682 seem to work just fine with either of the `pdf2png` or `pdf2svg` examples, see https://github.com/mozilla/pdf.js/tree/master/examples/node, when testing against the `master` version of the PDF.js library.

Given that this issue is over two years old, and that many improvements have been made since then (e.g. PR #11601 may *indirectly*  have fixed this); is it meaningful to keep this issue open?
