### ISSUE TITLE
Travis CI is suddenly failing on a unit test

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#9947]
From the logs:

```
Failures:
1) api getDocument creates pdf doc from URL
  Message:
    Expected false to equal true.
  Stack:
    Error: Expected false to equal true.
        at <Jasmine>
        at /home/travis/build/mozilla/pdf.js/build/lib/test/unit/api_spec.js:80:52
        at process._tickCallback (internal/process/next_tick.js:68:7)
```

This is strange because all checks were green when we merged the pull requests...

**Comment by timvandermeij** [comment]
Unfortunately there is also a passing build with `v10.8.0`, namely https://travis-ci.org/mozilla/pdf.js/builds/411182663. Only that one succeeded, the other ones failed.

**Comment by timvandermeij** [comment]
I removed all caches on Travis CI, but that also did not resolve the issue.
